(function(g){var window=this;'use strict';var Li=function(E){E.isActive()||E.start()},A8=function(E){var D={languageCode:E.languageCode,
languageName:E.languageName,displayName:g.tD(E),kind:E.kind,name:E.name,id:E.id,is_servable:E.Y,is_default:E.isDefault,is_translateable:E.isTranslateable,vss_id:E.vssId};E.xtags&&(D.xtags=E.xtags);E.captionId&&(D.captionId=E.captionId);E.translationLanguage&&(D.translationLanguage=E.translationLanguage);return D},PT0=function(E,D){var w=new g.nJ;
w.languageCode=E.languageCode;w.languageName=E.languageName;w.name=E.name;w.displayName=E.displayName;w.kind=E.kind;w.isDefault=!1;w.Y=E.Y;w.isTranslateable=E.isTranslateable;w.vssId=E.vssId;w.url=E.url;w.translationLanguage=D;E.xtags&&(w.xtags=E.xtags);E.captionId&&(w.captionId=E.captionId);return w},Ci=function(E,D){return D?E.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},SmR=function(E){return g.Hp(E)||E.X("web_enable_caption_language_preference_stickiness")},KqQ=async function(E,D){E=
E+"|"+D;
D=await g.kX();if(!D)throw g.zs("gct");return(await g.xE(D)).get("captions",E)},V07=function(E,D,w){KqQ(E,D).then(h=>{h&&w(h.trackData,new g.nJ(h.metadata))})},qs=function(E){if(!OyX.test(E))throw Error("'"+E+"' is not a valid hex color");
E.length==4&&(E=E.replace(c9R,"#$1$1$2$2$3$3"));E=E.toLowerCase();E=parseInt(E.slice(1),16);return[E>>16,E>>8&255,E&255]},f50=function(){var E={},D="suggest_correction"in g.AE?g.AE.suggest_correction:"Edit caption";
D=D||"";for(let w in E){let h=()=>String(E[w]);
D=D.replace(new RegExp("\\$\\{"+w+"\\}","gi"),h);D=D.replace(new RegExp("\\$"+w,"gi"),h)}return D},H4=function(){return g.TG("yt-player-caption-display-settings")},zKM=function(E,D){g.na(D,w=>E.equals(w))||D.push(E)},gS=function(E,D){switch(D.kind){case "asr":zKM(D,E.D);
break;default:zKM(D,E.A)}},mML=async function(E,D,w){E.A=g.Kq(D,w)},M0I=function(E,D){var w=g.KG(E.segments,D);
w>=0||w<0&&(-w-1)%2===1||(w=-w-1,w>0&&D-E.segments[w-1]===1&&w<E.segments.length&&E.segments[w]-D===1?(g.eg(E.segments,w),g.eg(E.segments,w-1)):w>0&&D-E.segments[w-1]===1?E.segments[w-1]=D:w<E.segments.length&&E.segments[w]-D===1?E.segments[w]=D:(g.aZ(E.segments,w,0,D),g.aZ(E.segments,w+1,0,D)))},Zyc=function(E){return E.Y&&E.Y.C?E.Y.C+E.player.Xc()<E.player.getCurrentTime():!1},Qga=function(E,D){if(E.policy.FH&&E.player.PC()){var w=g.A$(D,E.policy,{});
w.set("pot",E.player.PC());w=w.hD()}else w=g.A$(D,E.policy,{}).hD();var h={format:"RAW",withCredentials:!0};if(E.policy.GZ){h.method="POST";let P=D.N;P&&Object.keys(P).length>0?h.postBody=g.ih(P,g.wW):h.postBody=(0,g.zo)([120,0])}E.C&&(h.responseType="arraybuffer");var d=++E.NR,a=(0,g.X)();E.A=g.Qc(w,h,3,100,-1,P=>{P.errorCode==="net.timeout"&&E.player.W("capnt",{rn:d++})}).then(P=>{if(E.policy.bW&&d%100===1){var S=(0,g.X)();
E.player.W("caprsp",{rn:d,ms:S-a,kb:(P.xhr.responseText.length/1024).toFixed()})}a:{P=P.xhr;E.hT();if(E.D){var K=!(E.C?P.response:P.responseText)||P.status>=400;if(S=g.nw(P)){P=g.A$(E.D,E.policy,{});E.D.ZX(P,S);Qga(E,E.D);break a}K?E.player.W("capfail",{status:P.status}):(g.Hh("fcb_r",(0,g.X)(),E.player.getVideoData()?.Ga||""),S=E.D.x9[0],K=S.Ea,E.U!=null&&E.Z!==K&&(E.C?E.U(P.response,(S.segmentStartTime+E.player.Xc())*1E3):E.U(P.responseText,(S.segmentStartTime+E.player.Xc())*1E3),E.Z=K))}E.D=null;
E.A=null}}).Ty(P=>{E.D=null;
E.A=null;E.player.W("capfail",{rn:d,status:P.xhr?.status})});
E.D=D;M0I(E.N,E.D.x9[0].Ea)},jg0=function(E,D){return D!=null&&D in E.A.Y?E.A.Y[D]:null},LqX=function(E,D,w){var h=[];
for(let d in E.A.Y){if(!E.A.Y.hasOwnProperty(d))continue;let a=E.A.Y[d];if(g.Ry(a,w||null)){let P=a.info.captionTrack;P&&P.languageCode===D&&h.push(a)}}return h.length?h[0]:null},A9c=function(E,D){var w=[];
for(let d in E.A.Y){if(!E.A.Y.hasOwnProperty(d))continue;var h=E.A.Y[d];if(g.Ry(h,D||null)){let a=h.info.id,P=a,S=`.${a}`,K="",f="";if(h=h.info.captionTrack)a=h.languageCode,P=h.displayName,S=h.vssId,K=h.kind,f=h.id;w.push(new g.nJ({id:d,languageCode:a,languageName:P,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:S,kind:K,captionId:f}))}}return w},xi=function(E){if(typeof DOMParser!="undefined")return g.Q1(new DOMParser,g.jL(E),"application/xml");
throw Error("Your browser does not support loading xml documents");},CTo=function(E,D,w,h){var d=D/360*16;
D>=E&&(E=640,h>w*1.3&&(E=480),d=w/E*16);return d},qm$=function(E){var D=1+.25*(E.fontSizeIncrement||0);
if(E.offset===0||E.offset===2)D*=.8;return D},Hy7=function(E,D){var w="vertical-rl";
E.Y.J6===1&&(w="vertical-lr");g.XX&&(w=w==="vertical-lr"?"tb-lr":"tb-rl");g.Pg(D,"-o-writing-mode",w);g.Pg(D,"-webkit-writing-mode",w);g.Pg(D,"writing-mode",w);g.Pg(D,"text-orientation","upright");g.B3(D,"ytp-vertical-caption");E.D.params.sF===3&&(g.Pg(D,"text-orientation",""),g.Pg(D,"transform","rotate(180deg)"))},gvo=function(E,D){var w={},h=D.background?D.background:E.Y.ll.background;
if(D.backgroundOpacity!=null||D.background){var d=D.backgroundOpacity!=null?D.backgroundOpacity:E.Y.ll.backgroundOpacity;h=qs(h);w.background="rgba("+h[0]+","+h[1]+","+h[2]+","+d+")";E.TZ&&(w["box-decoration-break"]="clone",w["border-radius"]=`${E.YF*.25}px`)}if(D.fontSizeIncrement!=null||D.offset!=null)w["font-size"]=`${E.Kc*qm$(D)}px`;E.experiments.tT("enable_player_captions_new_style_defaults")&&(w["line-height"]="1.375");h=1;d=D.color||E.Y.ll.color;if(D.color||D.textOpacity!=null)d=qs(d),h=D.textOpacity==
null?E.Y.ll.textOpacity:D.textOpacity,d="rgba("+d[0]+","+d[1]+","+d[2]+","+h+")",w.color=d,w.fill=d;var a=D.charEdgeStyle;a===0&&(a=void 0);if(a){d=`rgba(34, 34, 34, ${h})`;let K=`rgba(204, 204, 204, ${h})`;D.j_&&(K=d=D.j_);let f=E.Kc/16/2,m=Math.max(f,1);var P=Math.max(2*f,1),S=Math.max(3*f,1);let M=Math.max(5*f,1);h=[];switch(a){case 4:for(;S<=M;S+=f)h.push(`${P}px ${P}px ${S}px ${d}`);break;case 1:P=window.devicePixelRatio>=2?.5:1;for(a=m;a<=S;a+=P)h.push(`${a}px ${a}px ${d}`);break;case 2:h.push(`${m}px ${m}px ${K}`);
h.push(`-${m}px -${m}px ${d}`);break;case 3:for(S=0;S<5;S++)h.push(`0 0 ${P}px ${d}`)}w["text-shadow"]=h.join(", ")}d="";switch(D.fontFamily){case 1:d='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:d='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:d='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:d='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:d='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:d=g.RK()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:d='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}d&&(w["font-family"]=d);d=D.offset;d==null&&(d=E.Y.ll.offset);switch(d){case 0:w["vertical-align"]="sub";break;case 2:w["vertical-align"]="super"}D.fontFamily===7&&(w["font-variant"]="small-caps");D.bold&&(w["font-weight"]="bold");D.italic&&(w["font-style"]="italic");D.underline&&
(w["text-decoration"]="underline");D.I8&&(w.visibility="hidden");D.GV===1&&E.Z&&(w["text-combine-upright"]="all",w["text-orientation"]="mixed",d=g.rT||g.OJ,E.D.params.sF===3?w.transform=d?"rotate(90deg)":"rotate(180deg)":d&&(w.transform="rotate(-90deg)"));if(D.textEmphasis===1||D.textEmphasis===2||D.textEmphasis===3||D.textEmphasis===4||D.textEmphasis===5)if(g.rT)w["font-weight"]="bold";else switch(w["text-emphasis-style"]="filled circle",w["text-emphasis-color"]="currentcolor",w["webkit-text-emphasis"]=
"filled circle",D.textEmphasis){case 4:case 3:w["text-emphasis-position"]="under left";w["webkit-text-emphasis-position"]="under left";break;case 5:case 2:w["text-emphasis-position"]="over right",w["webkit-text-emphasis-position"]="over right"}return w},xM7=function(E,D){if(E.Oa&&D.length===0)return 0;
E=1;for(let w=0;w<D.length;w++){let h=D[w];typeof h.text==="string"&&(E+=h.text.split("\n").length-1,h.append||w===0||E++)}return E},Yi=function(E){E=E.split("px");
return E.length>0?(E=Number(E[0]))?E:0:0},Wq0=function(E,D,w){E.qR=E.qR||!!w;
var h={};Object.assign(h,E.Y.ll);Object.assign(h,w||D.Y);Object.assign(h,E.ta.ll);(w=!E.G)&&YmX(E);var d=E.jQ&&E.gi&&g.Qw(h,E.gi)?E.jQ:I5L(E,h),a=typeof D.text==="string",P=a?D.text.split("\n"):[D.text];for(let K=0;K<P.length;K++){var S=K>0||!D.append;let f=P[K];S&&!w?(YmX(E),d=I5L(E,h)):S&&w&&(w=!1);f&&(d.appendChild(a?g.$z(f):f),a||f.tagName!=="RUBY"||f.childElementCount!==4||g.rT||!g.fj(f.children[2],"text-emphasis")||(S=E.Z?"padding-right":"padding-top",g.fj(f.children[2],"text-emphasis-position")&&
(S=E.Z?"padding-left":"padding-bottom"),g.F$?g.Pg(d,S,"1em"):g.Pg(d,S,"0.5em")))}E.gi=h;E.jQ=d;E.B.push(D)},YmX=function(E){if(E.G){var D=E.G;
if(E.TZ){var w=E.Y.textAlign;w===0?(D=D.firstElementChild)&&g.Pg(D,{"border-bottom-left-radius":"0"}):w===1&&(D=D.lastElementChild)&&g.Pg(D,{"border-bottom-right-radius":"0"})}}E.G=g.X$("SPAN");g.Pg(E.G,{display:"block"});g.B3(E.G,"caption-visual-line");E.C.appendChild(E.G)},I5L=function(E,D){var w=g.X$("SPAN");
g.Pg(w,{display:"inline-block","white-space":"pre-wrap"});g.Pg(w,gvo(E,D));w.classList.add("ytp-caption-segment");E.G.appendChild(w);E.TZ&&E.C.children.length>1&&(E=E.Y.textAlign,E===0?w.previousElementSibling||g.Pg(w,{"border-top-left-radius":"0"}):E===1&&g.Pg(w,{"border-top-right-radius":"0"}));w.previousElementSibling&&(g.Pg(w.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Pg(w,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return w},
r9c=function(E,D,w){if(E===255&&D===255||!E&&!D)return{sW:E,
t5:D,result:0};E=TtL[E];D=TtL[D];if(E&128){var h;if(h=!(D&128))h=D,h=w.xD()&&w.t5===h;if(h)return{sW:E,t5:D,result:1}}else if(D&128&&1<=E&&E<=31)return{sW:E,t5:D,result:2};return{sW:E,t5:D,result:3}},byX=function(E,D,w,h){D===255&&w===255||!D&&!w?(++E.D===45&&E.reset(),E.N.A.clear(),E.C.A.clear()):(E.D=0,Bta(E.N,D,w,h))},ov8=function(E,D){E.Y.sort((w,h)=>{var d=w.time-h.time;
return d===0?w.order-h.order:d});
for(let w of E.Y)E.time=w.time,w.type===0?byX(E,w.kQ,w.MO,D):w.type===1&&E.A&496&&Bta(E.C,w.kQ,w.MO,D);E.Y.length=0},l57=function(E,D){switch(E){case 0:return FqR[(D&127)-32];
case 1:return RKo[D&15];case 2:return NtR[D&31];case 3:return y98[D&31]}return 0},If=function(E,D){if(E.style.type===3){var w=0,h=0,d=E.C.time+0,a="",P="",S=d;
for(var K=1;K<=15;++K){var f=!1;for(var m=h?h:1;m<=32;++m){var M=E.D[K][m];if(M.Y!==0){w===0&&(w=K,h=m);f=String.fromCharCode(M.Y);var L=M.timestamp;L<d&&(d=L);M.timestamp=S;P&&(a+=P,P="");a+=f;f=!0}if((M.Y===0||m===32)&&f){P="\n";break}else if(h&&!f)break}if(w&&!f)break}a&&D.N(w,h,d,S,a)}else for(h=w=0,a=d=E.C.time+0,P=1;P<=15;++P)for(S="",K=1;K<=32;++K)if(m=E.D[P][K],M=m.Y,M!==0&&(w===0&&(w=P,h=K),f=String.fromCharCode(M),L=m.timestamp,L<=d&&(d=L),S+=f,m.reset()),K===32||M===0)S&&D.N(w,h,d,a,S),
d=a,S="",h=w=0},W4=function(E){return E.D[E.row][E.A]},T5=function(E,D,w){D>=2&&E.A>1&&(--E.A,W4(E).Y=0);
var h=W4(E);h.timestamp=E.C.time+0;h.Y=l57(D,w);E.A<32&&E.A++},UMo=function(E,D,w,h){for(let P=0;P<h;P++)for(let S=0;S<=32;S++){var d=E.D[D+P][S],a=E.D[w+P][S];
d.Y=a.Y;d.timestamp=a.timestamp}},rS=function(E,D,w){for(let h=0;h<w;h++)for(let d=0;d<=32;d++)E.D[D+h][d].reset()},B4=function(E){E.row=E.Y>0?E.Y:1;
E.A=1;rS(E,0,15)},iya=function(E){E.style.set(1);
E.Y=E.N;E.Y.Y=0;E.Y.style=E.style;E.D.mode=1<<E.Y.N},b6=function(E,D,w){var h=E.A,d=!1;
switch(E.style.get()){case 4:case 1:case 2:E.style.get()===4&&h.Y>0||(If(h,w),B4(E.A),B4(E.N),h.row=15,h.Y=D,d=!0)}E.style.set(3);E.Y=h;E.Y.style=E.style;E.D.mode=1<<h.N;d?h.A=1:h.Y!==D&&(h.Y>D?(If(h,w),rS(h,h.row-h.Y,D)):h.row<D&&(D=h.Y),h.Y=D)},J9M=function(E){E.style.set(4);
E.Y=E.text;E.Y.style=E.style;E.D.mode=1<<E.Y.N},Bta=function(E,D,w,h){E.A.update();
D=r9c(D,w,E.A);switch(D.result){case 0:return;case 1:case 2:return}var d=D.sW;D=D.t5;if(32<=d||!d)E.Y.mode&E.Y.A&&(w=d,w&128&&(w=127),D&128&&(D=127),E=E.N.Y,w&96&&T5(E,0,w),D&96&&T5(E,0,D),w!==0&&D!==0&&E.style.type===3&&If(E,h));else if(d&16)a:if(!E.A.matches(d,D)&&(w=E.A,w.sW=d,w.t5=D,w.state=2,w=d&8?E.Z:E.D,E.N=w,E.Y.mode=1<<(E.C<<2)+(w.C<<1)+(w.style.type===4?1:0),(E.Y.mode|1<<(E.C<<2)+(w.C<<1)+(w.style.type!==4?1:0))&E.Y.A))if(D&64){h=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(d&7)<<1|D>>5&1];
E=D&16?((D&14)>>1)*4:0;D=w.Y;switch(w.style.get()){case 4:h=D.row;break;case 3:if(h!==D.row){if(h<D.Y&&(h=D.Y,h===D.row))break;var a=1+D.row-D.Y;let P=1+h-D.Y;UMo(D,P,a,D.Y);w=a;d=D.Y;P<a?(a=P+d-a,a>0&&(w+=a,d-=a)):(a=a+d-P,a>0&&(d-=a));rS(D,w,d)}}D.row=h;D.A=E+1}else switch(d&7){case 1:switch(D&112){case 32:T5(w.Y,0,32);break a;case 48:D===57?(h=w.Y,W4(h).Y=0,h.A<32&&h.A++):T5(w.Y,1,D&15)}break;case 2:D&32&&T5(w.Y,2,D&31);break;case 3:D&32&&T5(w.Y,3,D&31);break;case 4:case 5:if(32<=D&&D<=47)switch(D){case 32:iya(w);
break;case 33:h=w.Y;h.A>1&&(--h.A,W4(h).Y=0);break;case 36:h=w.Y;E=W4(h);for(D=0;D<=15;D++)for(w=0;w<=32;w++)if(h.D[D][w]===E){for(;w<=32;w++)h.D[D][w].reset();break}break;case 37:b6(w,2,h);break;case 38:b6(w,3,h);break;case 39:b6(w,4,h);break;case 40:T5(w.Y,0,32);break;case 41:h=w;h.style.set(2);h.Y=h.A;h.Y.Y=0;h.Y.style=h.style;h.D.mode=1<<h.Y.N;break;case 42:h=w;E=h.text;E.Y=15;E.style.set(4);B4(E);J9M(h);break;case 43:J9M(w);break;case 44:E=w;D=E.A;switch(E.style.get()){case 1:case 2:case 3:If(D,
h)}rS(D,0,15);break;case 45:b:{D=w;E=D.Y;switch(D.style.get()){default:case 2:case 1:break b;case 4:if(E.row<15){++E.row;E.A=1;break b}break;case 3:}E.Y<2&&(E.Y=2,E.row<E.Y&&(E.row=E.Y));D=E.row-E.Y+1;If(E,h);UMo(E,D,D+1,E.Y-1);rS(E,E.row,1)}break;case 46:rS(w.N,0,15);break;case 47:E=w,If(E.A,h),E.N.updateTime(E.D.time+0),h=E.N,E.N=E.A,E.A=h,iya(E)}break;case 7:switch(D){case 33:case 34:case 35:h=w.Y,(h.A+=D&3)>32&&(h.A=32)}}},vvL=function(E,D,w,h,d,a,P){var S=a[0],K=P[S.getAttribute("p")];
if(K.L6===1){var f=a[1],m=a[2];a=a[3];S.getAttribute("t");f.getAttribute("t");m.getAttribute("t");a.getAttribute("t");S.getAttribute("p");f.getAttribute("p");a.getAttribute("p");P=P[m.getAttribute("p")];S=p90(S.textContent,f.textContent,m.textContent,a.textContent,P);return new of(E,D,d,w,S,h,K)}switch(K.L6){case 9:case 10:K.textEmphasis=1;break;case 11:K.textEmphasis=2;break;case 12:K.textEmphasis=3;break;case 13:K.textEmphasis=4;break;case 14:K.textEmphasis=5}return new of(E,D,d,w,S.textContent||
"",h,K)},p90=function(E,D,w,h,d){var a=g.RK(),P=a?g.X$("DIV"):g.X$("RUBY"),S=g.X$("SPAN");
S.textContent=E;P.appendChild(S);E=a?g.X$("DIV"):g.X$("RP");E.textContent=D;P.appendChild(E);D=a?g.X$("DIV"):g.X$("RT");D.textContent=w;P.appendChild(D);w=d.L6;if(w===10||w===11||w===12||w===13||w===14)if(g.Pg(D,"text-emphasis-style","filled circle"),g.Pg(D,"text-emphasis-color","currentcolor"),g.Pg(D,"webkit-text-emphasis","filled circle"),d.L6===11||d.L6===13)g.Pg(D,"webkit-text-emphasis-position","under left"),g.Pg(D,"text-emphasis-position","under left");w=!0;if(d.L6===4||d.L6===7||d.L6===12||
d.L6===14)g.Pg(P,"ruby-position","over"),g.Pg(P,"-webkit-ruby-position","before");else if(d.L6===5||d.L6===6||d.L6===11||d.L6===13)g.Pg(P,"ruby-position","under"),g.Pg(P,"-webkit-ruby-position","after"),w=!1;d=a?g.X$("DIV"):g.X$("RP");d.textContent=h;P.appendChild(d);a&&(h=w,g.Pg(P,{display:"inline-block",position:"relative"}),a=P.firstElementChild.nextElementSibling,g.Pg(a,"display","none"),a=a.nextElementSibling,g.Pg(a,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Pg(P.lastElementChild,"display","none"),h?(g.Pg(P,"padding-top","0.6em"),g.Pg(a,"top","0")):(g.Pg(P,"padding-bottom","0.6em"),g.Pg(a,"bottom","0")));return P},X97=function(E){var D="_"+Fn++;
return new Rf(0,0x8000000000000,0,D,E)},Ns=function(E,D){E=E.getAttribute(D);
if(E!=null)return Number(E)},y6=function(E,D){E=E.getAttribute(D);
if(E!=null)return E==="1"},l6=function(E,D){E=Ns(E,D);
return E!==void 0?E:null},i6=function(E,D){E=E.getAttribute(D);
if(E!=null)return U4.test(E),E},$MM=function(E,D){var w={},h=D.getAttribute("ws");
Object.assign(w,h?E.B[h]:E.N);E=l6(D,"mh");E!=null&&(w.oL=E);E=l6(D,"ju");E!=null&&(w.textAlign=E);E=l6(D,"pd");E!=null&&(w.sF=E);E=l6(D,"sd");E!=null&&(w.J6=E);E=i6(D,"wfc");E!=null&&(w.windowColor=E);D=Ns(D,"wfo");D!==void 0&&(w.windowOpacity=D/255);return w},ufR=function(E,D){var w={},h=D.getAttribute("wp");
h&&Object.assign(w,E.U[h]);E=l6(D,"ap");E!=null&&(w.Ku=E);E=Ns(D,"cc");E!=null&&(w.V6=E);E=Ns(D,"ah");E!=null&&(w.nh=E);E=Ns(D,"rc");E!=null&&(w.gh=E);D=Ns(D,"av");D!=null&&(w.mI=D);return w},nvL=function(E,D,w,h){var d={};
Object.assign(d,ufR(E,D));Object.assign(d,$MM(E,D));h?g.Qw(d,E.N)?(h=E.C,d=E.N):h="_"+Fn++:h=D.getAttribute("id")||"_"+Fn++;E=Ns(D,"t")+w;D=Ns(D,"d")||0x8000000000000;if(d.sF===2||d.sF===3)w=d.gh,d.gh=d.V6,d.V6=w;return new Rf(E,D,0,h,d)},J8=function(E){E=g.uL(Math.round(E),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-E.length)+E},Gha=function(E,D,w,h,d){h===0&&(h=0x8000000000000);
var a={};D.wpWinPosId&&Object.assign(a,E.N.get(D.wpWinPosId));D.wsWinStyleId&&Object.assign(a,E.C.get(D.wsWinStyleId));E=D.rcRowCount;E!==void 0&&(a.gh=E);D=D.ccColCount;D!==void 0&&(a.V6=D);if(a.sF===2||a.sF===3)D=a.gh,a.gh=a.V6,a.V6=D;return new Rf(w,h,0,d,a)},pi=function(E){var D=E.byteOffset;
E.byteOffset+=1;return E.Y.getUint8(D)},v4=function(E){var D=E.byteOffset;
E.byteOffset+=4;return E.Y.getUint32(D)},sgo=function(E){if(typeof E==="string")return!1;
E=new t0c(E,0);return khc(E)},khc=function(E){if(!(E.byteOffset<E.Y.byteLength)||v4(E)!==1380139777)return!1;
E.version=pi(E);if(E.version>1)return!1;pi(E);pi(E);pi(E);return!0},eKR=function(E,D){if(!D)return"";
E.Z&&E.D.params.J6!==1&&(D*=-1);return`translate${E.Z?"X":"Y"}(${D}px)`},E1$=function(E){E.Ua=Array.from(E.element.getElementsByClassName("caption-visual-line"));
for(var D=E.D.params.gh,w=0,h=0,d=E.Ua.length-1;w<D&&d>-1;){var a=E.Ua[d];h+=E.Z?a.offsetWidth:a.offsetHeight;w++;d--}E.NR=h;D=Math;w=D.max;isNaN(E.GZ)&&((h=E.Y.V6)?(d=g.X$("SPAN"),g.kz(d,"\u2013".repeat(h)),g.Pg(d,gvo(E,E.Y.ll)),E.C.appendChild(d),E.GZ=d.offsetWidth,E.C.removeChild(d)):E.GZ=0);h=E.C;E.eQ=w.call(D,E.GZ,E.Sp,(E.Z?h.offsetHeight:h.offsetWidth)+1)},D4L=function(E,D){E1$(E);
var w=E.Ua.reduce((h,d)=>(E.Z?d.offsetWidth:d.offsetHeight)+h,0);
w=E.NR-w;if(w!==E.sa){let h=w>0&&E.sa===0,d=w<E.sa;D||isNaN(w)||h||!d||(g.B3(E.element,"ytp-rollup-mode"),E.O(E.element,"transitionend",E.ZB));g.Pg(E.C,"transform",eKR(E,w));E.sa=w}E1$(E)},h5$=function(E,D,w,h){var {formatId:d,
Ea:a,startTimeMs:P,durationMs:S}=E.G(D),K={formatId:d,startTimeMs:P,durationMs:S,Yo:a,aU:a},f=wVX(E.Jt,K.startTimeMs),m=f>=0?E.Jt[f]:null,M=m?m.startTimeMs+m.durationMs:0,L=K.startTimeMs+K.durationMs;!m||K.startTimeMs-M>E.N?E.Jt.splice(f+1,0,K):(m.durationMs=Math.max(M,L)-m.startTimeMs,m.aU=Math.max(m.aU,K.aU));h(E.Jt);h=g.NQ(D);E=E.C;h=h.buffer.slice(h.byteOffset,h.byteLength+h.byteOffset);D=D.info.N;E.Y9?E.U==null?g.ov(E.logger,350058965,"Null loaded track meta data at captions data received"):
w.X8(h,E.U,D*1E3):g.ov(E.logger,350058965,"Null Representation at captions data received")},PlM=function(E,D){E.A=(w,h)=>{if(E.K.L().experiments.tT("html5_sabr_live_support_subfragmented_captions"))(E.Y?E.Y=E.Y.C(w):(E.Y=w,d40(E.Y)),E.Y)?w.info.KM&&(aBc(E.Y),h5$(E,E.Y,D,h),E.Y=null):g.ov(E.logger,350058965,"Empty slice");
else if(w.info.KM){var d=w;if(E.Gf.length>0){for(d=E.Gf.shift();E.Gf.length>0;)d=d?.C(E.Gf.shift());d=d?.C(w)}d?(d40(d),aBc(d),h5$(E,d,D,h)):g.ov(E.logger,350058965,"Empty slice")}else E.Gf.push(w)};
E.K.addEventListener("sabrCaptionsDataLoaded",E.A)},wVX=function(E,D){E=g.KG(E,{startTimeMs:D},(w,h)=>w.startTimeMs-h.startTimeMs);
return E>=0?E:-E-2},d40=function(E){try{var D=g.iR(E)*1E3}catch(w){D=E.info.segmentStartTime*1E3}D<0&&(D=E.info.segmentStartTime*1E3);
E.info.segmentStartTime=D/1E3;E.info.N=D/1E3},aBc=function(E){try{var D=g.$b(E)*1E3}catch(w){D=E.info.D*1E3}D<0&&(D=E.info.D*1E3);
E.info.D=D/1E3;E.info.G=D/1E3},SdQ=function(E,D){if(!g.vr(E)||E.Y!=null&&g.Fh(D,E.Y)&&E.Y.Y.rawcc!=null)return!1;
D=!!E.Y&&E.Y.isManifestless&&Object.values(E.Y.Y).some(w=>g.Ry(w,"386"));
E=!!E.Y&&!E.Y.isManifestless&&g.ze(E.Y);return D||E},KBR=function(E,D,w){var h=[];
for(let d in E.A.Y){if(!E.A.Y.hasOwnProperty(d))continue;let a=E.A.Y[d];if(g.Ry(a,w||null)){let P=a.info.captionTrack;P&&P.languageCode===D&&h.push(a)}}return h.length?h[0]:null},V6Q=function(E,D){var w=[];
for(let d in E.A.Y){if(!E.A.Y.hasOwnProperty(d))continue;var h=E.A.Y[d];if(g.Ry(h,D||null)){let a=h.info.id,P=a,S=`.${a}`,K="",f="";if(h=h.info.captionTrack)a=h.languageCode,P=h.displayName,S=h.vssId,K=h.kind,f=h.id;w.push(new g.nJ({id:d,languageCode:a,languageName:P,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:S,kind:K,captionId:f}))}}return w},cI$=function(E){var D=OBR.length;
if(E.byteLength<D)return!1;E=new Uint8Array(E,0,D);for(let w=0;w<D;w++)if(OBR[w]!==E[w])return!1;return!0},Xn=function(E){E=E.split(":");
var D=0;for(let w of E)D=D*60+Number(w);return D*1E3},fB7=function(E,D,w,h){h=Object.assign({oL:0},h);
return new Rf(E,D,w,"_"+Fn++,h)},z5L=function(E,D,w,h,d,a,P,S,K){switch(P.tagName){case "b":S.bold=!0;
break;case "i":S.italic=!0;break;case "u":S.underline=!0}for(let m=0;m<P.childNodes.length;m++){var f=P.childNodes[m];if(f.nodeType===3)f=new of(D,w,h,d.id,f.nodeValue,a||m>0,g.mx(S)?void 0:S),K.push(f),d.Y.push(f);else{let M={};Object.assign(M,S);z5L(E,D,w,h,d,!0,f,M,K)}}},M67=function(E,D,w){if(typeof D==="string"||sgo(D))return[{trackData:D,
AA:w}];if(typeof D==="string"&&D.substring(0,6)==="WEBVTT"||typeof D!=="string"&&cI$(D))return[{trackData:D,AA:w}];var h=new DataView(D);if(h.byteLength<=8||h.getUint32(4)!==1718909296)return[];var d=g.cP(h);if(E.SE&&d){var a=g.uM(d),P=g.nf(d);d=d.segmentNumber;a&&d&&E.SE.Cj(d,a,P)}E=g.Ku(h,1835295092);if(!E||!E.length||!E[0].size)return[];a=[];for(P=0;P<E.length;P++)d=E[P],d=new Uint8Array(D,d.dataOffset,d.size-(d.dataOffset-d.offset)),d=g.CF(d),a.push({trackData:d,AA:w+P*1E3});m4X(h,a,w);return a=
a.filter(S=>!!S.trackData)},QqR=function(E,D,w){E.Y||(E.Y=new ZB$);
E=E.Y.D(D,w);Math.random()<.01&&g.c6(Error("Deprecated subtitles format in web player: WebVTT"));return E},m4X=function(E,D,w){var h=g.eK(E,0,1836476516),d=9E4;
h&&(d=g.wb(h)||9E4);h=0;var a=g.Ku(E,1836019558);for(let S=0;S<a.length;S++){var P=a[S];S<D.length&&(P=g.eK(E,P.dataOffset,1953653094))&&(P=g.eK(E,P.dataOffset,1952867444))&&(P=g.PP(P)/d*1E3,S===0&&(h=P),D[S].AA=P-h+w||w*S*1E3)}},jqX=function(E){var D={};
if(E=g.kI(E))D.lang=E,g.qYc.test(E)&&(D.sF=1);return D},$i=function(E){return E.D==="HLS"&&E.Qg?!0:E.qR&&E.Qg&&E.D!=="LIVE"&&E.D!=="SABR_LIVE"},LB7=function(E){return!E.N&&E.qR&&E.Oa&&(E.D==="LIVE"||E.D==="SABR_LIVE")},u6=function(E,D,w=!1){var h=E.J.X("enable_player_captions_new_style_defaults")?AIR:ClI,d=h.ll;
E.C={};Object.assign(E.C,h);E.C.ll={};Object.assign(E.C.ll,d);E.Z={ll:{}};var a=D.backgroundOverride?E.Z:E.C,P=D.background||d.background;U4.test(P);a.ll.background=P;a=D.colorOverride?E.Z:E.C;P=D.color||d.color;U4.test(P);a.ll.color=P;a=D.windowColorOverride?E.Z:E.C;P=D.windowColor||h.windowColor;U4.test(P);a.windowColor=P;a=D.backgroundOpacityOverride?E.Z:E.C;P=D.backgroundOpacity;P==null&&(P=d.backgroundOpacity);a.ll.backgroundOpacity=P;a=D.fontSizeIncrementOverride?E.Z:E.C;P=D.fontSizeIncrement;
P==null&&(P=d.fontSizeIncrement);a.ll.fontSizeIncrement=P;P=D.fontStyleOverride?E.Z:E.C;a=D.fontStyle;a==null&&(a=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);P=P.ll;switch(a){case 1:P.bold=!0;delete P.italic;break;case 2:delete P.bold;P.italic=!0;break;case 3:P.bold=!0;P.italic=!0;break;default:delete P.bold,delete P.italic}a=D.textOpacityOverride?E.Z:E.C;P=D.textOpacity;P==null&&(P=d.textOpacity);a.ll.textOpacity=P;a=D.windowOpacityOverride?E.Z:E.C;P=D.windowOpacity;P==null&&(P=h.windowOpacity);a.windowOpacity=
P;h=D.charEdgeStyleOverride?E.Z:E.C;a=D.charEdgeStyle;a==null&&(a=d.charEdgeStyle);h.ll.charEdgeStyle=a;h=D.fontFamilyOverride?E.Z:E.C;a=D.fontFamily;a==null&&(a=d.fontFamily);h.ll.fontFamily=a;E.loaded&&E.VC();w&&g.WW("yt-player-caption-display-settings",D,2592E3)},ni=function(E,D,w){D&&!E.V?(D=X97({sF:0,
lang:"en"}),E.V=[D,new of(D.start,D.end-D.start,0,D.id,w??"Captions look like this")],E.player.kE(E.V)):!D&&E.V&&(qdX(E,E.V),E.V=null)},g1I=function(E){if(E.J.X("enable_player_captions_persistence_state_machine")){var D=g.TG("yt-player-caption-persistence");
if(D==null){let w=g.Ro().a9(65);if(w===!0)D=!1;else{let h=g.Hp(E.J)?G5(E):HBo(E);h!=null?D=!!h:w===!1&&(D=!0)}D!==void 0&&t8(E,D)}return D}},G5=function(E){if(!E.K.isInline())return g.TG("yt-player-sticky-caption")},HBo=function(E){if(!E.storage)return null;
try{var D=E.storage.get("module-enabled")}catch(w){E.storage.remove("module-enabled")}return D},ki=function(E){if(E.J.X("enable_player_captions_persistence_state_machine"))return g1I(E);
var D=void 0,w=g.Ro().a9(65);if(g.Hp(E.J)&&w!=null){if(G5(E)!=null)return!1;D=!w}return D},x4$=function(E){if(E.J.j2===1||E.videoData.s2===1||g.bZ(E.videoData,"yt:cc")==="alwayson")return!0;
if(E.videoData.captionTracks.length)var D=E.getAudioTrack().A;if(E.J.X("enable_player_captions_persistence_state_machine")){var w=g1I(E);if(w!==void 0)return!!w}else if(E.J.j2===2&&(g.Hp(E.J)?w=G5(E):w=HBo(E),w!=null))return!!w;w=Ci(E.player.getAudioTrack(),g.Hp(E.J));var h=g.bZ(E.videoData,"yt:cc");if(ki(E)===void 0){if(w==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return h?h==="on":!0;if(w==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return h==="on"}else return h==="on";return D==="ON"||g.bZ(E.videoData,
"yt:cc")==="on"},s4=function(E,D=!1){if(E.A&&!D||!E.videoData.captionTracks.length)return!1;
E=E.getAudioTrack();return!!E.Y||E.A==="FORCED_ON"},Ydo=function(E){return E.J.X("html5_honor_caption_availabilities_in_audio_track")&&E.D!=="LIVE"&&E.D!=="SABR_LIVE"},IBa=function(E,D){if(E.A){var w=E.K.Ez().TH().textTracks,h=null;
E.D==="HLS"?h=E.A.getId():h=E.A.toString();for(let a=0;a<w.length;a++){var d=w[a];d.id===h&&(D?d.mode!=="showing"&&(d.mode="showing",d=E.A,E.D5(d,!!d,e9(E)?"g":E.U?"m":"s")):d.mode==="showing"&&(d.mode="disabled"))}}},e9=function(E){var D=Ey(E);
return!!D&&E.A===D},WB$=function(E,D){if(E.D==="HLS")return!1;
g.Jx(E.videoData)&&(D=!0);D||(D=E.D==="TTS"?!1:E.D==="INNERTUBE"?!1:!0);return D||E.J.X("web_watch_disable_account_level_captions_settings")&&g.Hp(E.J)?!0:!!g.Ro().a9(66)},Ey=function(E){return E.B&&E.B.Y},De=function(E,D){if(!E.Y)return null;
if(E.B&&E.B.N)return E.B.N;D=WB$(E,D);D=E.Y.Y.Y(D);var w=null;if(SmR(E.J)){var h=E.K.isInline()?void 0:g.TG("yt-player-caption-sticky-language");var d=[h,E.videoData.captionsLanguagePreference,E.J.captionsLanguagePreference,g.bZ(E.videoData,"yt:cc_default_lang")];let S=!1;for(let K=0;K<d.length;K++){let f=d[K];if(f){S=!0;for(var a=0;a<D.length;a++)if(g.kI(D[a])===f)return D[a];for(a=0;a<D.length;a++)if(g.kI(D[a]).split("-")[0]===f.split("-")[0])return D[a]}}if(S&&E.Y&&(d=E.Y.B,d.length))for(var P of d)if(P.languageCode===
h){w=P;break}}else for(P=[E.videoData.captionsLanguagePreference,E.J.captionsLanguagePreference,g.bZ(E.videoData,"yt:cc_default_lang")],h=0;h<P.length;h++)for(d=0;d<D.length;d++)if(g.kI(D[d])===P[h])return D[d];P=null;E.B&&E.B.D&&(P=E.B.D);P||(P=D.find(S=>S.isDefault)||null);
P||(P=D[0]||Ey(E));P&&w&&g.kI(P).split("-")[0]!==w.languageCode.split("-")[0]&&(P=PT0(P,w));return P},a3=function(E,D,w){E.loaded&&E.unload();
w!=null&&(E.U=w,E.U&&(E.J.X("enable_player_captions_persistence_state_machine")?t8(E,!!D):g.Hp(E.J)?wE(E,!!D):hY(E,!!D)));D!==null||s4(E,!0)||E.D5(D,!!D,E.U?"m":"s");E.A=D;s4(E)&&(E.A=Ey(E));dE(E,E.A??void 0);E.load()},t8=function(E,D){E.J.X("enable_player_captions_persistence_state_machine")&&g.WW("yt-player-caption-persistence",D,3122064E3)},wE=function(E,D){E.K.isInline()||g.WW("yt-player-sticky-caption",D,2592E3)},hY=function(E,D){if(E.storage)try{E.storage.set("module-enabled",D)}catch(w){}},
dE=function(E,D){E.J.X("html5_modify_caption_vss_logging")&&(E.videoData.k$=D)},rII=function(E,D){var w=E.eQ[D.id];
w&&w.D!==D&&(w.dispose(),delete E.eQ[D.id],w=null);w||(w=ThL(E,D))&&(E.eQ[D.id]=w)},Bh0=function(E,D){var w=D.windowId;
E.gi[w]||(E.gi[w]=[]);E.gi[w].push(D)},ThL=function(E,D){var w=bB0(E);
if(!w)return null;var h=E.A?g.kI(E.A):null;h&&g.qYc.test(h)&&(D.params.sF=1);var d=E.ZB.getPlayerSize();h=d.height*E.NR.height;d=d.width*E.NR.width;E.J.playerStyle!=="google-live"||E.C.isDefault||Object.assign(D.params,E.C);switch(D.params.oL!=null?D.params.oL:D.Y.length>1?1:0){case 1:return new o1$(D,E.C,E.Z,w.width,w.height,d,h,E.J.experiments,E.YF.bind(E),E.K);case 2:return new FB7(D,E.C,E.Z,w.width,w.height,d,h,E.J.experiments,E.YF.bind(E),E.K);default:return new PI(D,E.C,E.Z,w.width,w.height,
d,h,E.J.experiments,E.YF.bind(E),E.K)}},bB0=function(E){var D=E.ZB.getVideoContentRect(!0).height,w=E.ZB.getVideoContentRect(!0).width;
if(!D||!w)return null;D*=E.NR.height;w*=E.NR.width;return{width:w,height:D}},qdX=function(E,D){E.player.lx(D);
for(let w of D)g.EB(E.Ua,w);Li(E.GZ)},R5$=function(E,D){if(!E.Y)return{};
if(D){g.mx(D)||E.F7(D.vss_id,"m");if(E.N&&E.D!=="HLS"||!g.L8(D))return;if(g.mx(D)){a3(E,null,!0);return}let h;var w=E.Y.Y.Y(!0);for(let d=0;d<w.length;d++){let a=w[d];a.languageCode!==D.languageCode||h&&(a.languageName!==D.languageName||(a.captionId||"")!==(D.captionId||"")||g.tD(a)!==D.displayName)||(h=D.translationLanguage?PT0(a,D.translationLanguage):a)}E.ND(D.position);!h||h===E.A&&E.loaded||(D=g.Hq(),w=g.kI(h),D.length&&w===D[D.length-1]||(D.push(w),g.WW("yt-player-caption-language-preferences",
D)),SmR(E.J)&&!E.K.isInline()&&g.WW("yt-player-caption-sticky-language",w,2592E3),a3(E,h,!0))}else return E.loaded&&E.A&&!e9(E)?A8(E.A):{};return""};
g.Ww.prototype.Cj=g.wQ(134,function(E,D,w){this.A.set(E,{YG:D,Jd:w})});
g.Tn.prototype.Cj=g.wQ(133,function(E,D,w){this.zZ.Cj(E,D,w)});
g.Z2.prototype.U=g.wQ(132,function(){this.mediaElement.U()});
g.fS.prototype.U=g.wQ(131,function(){var E=g.rd(document,"track",void 0,this.Y);for(let D=0;D<E.length;D++)g.Gp(E[D])});
g.Z2.prototype.sa=g.wQ(130,function(){return this.mediaElement.sa()});
g.fS.prototype.sa=g.wQ(129,function(){return!(!this.Y.textTracks||!this.Y.textTracks.addEventListener)});
g.Z2.prototype.gi=g.wQ(128,function(){return this.mediaElement.gi()});
g.fS.prototype.gi=g.wQ(127,function(){return!!this.Y.textTracks});
g.Z2.prototype.NR=g.wQ(126,function(E){this.mediaElement.NR(E)});
g.fS.prototype.NR=g.wQ(125,function(E){for(let D=0;D<E.length;D++)this.Y.appendChild(E[D])});
g.E2.prototype.F7=g.wQ(48,function(E,D){this.app.Lc().F7(E,D)});
g.$U.prototype.F7=g.wQ(47,function(E,D){this.S.F7(E,D)});
g.MK.prototype.F7=g.wQ(46,function(E,D){E=[E,D];g.i9(this,g.pA(this.provider),"cfi",E)});
g.jc.prototype.F7=g.wQ(45,function(E,D){this.qoe&&this.qoe.F7(E,D)});
g.X_.prototype.F7=g.wQ(44,function(E,D){this.Te.F7(E,D)});
g.gu.prototype.F7=g.wQ(43,function(){});
g.vn.prototype.F7=g.wQ(42,function(E,D){g.jS(this,37,[E,D])});
g.E2.prototype.D5=g.wQ(41,function(E,D,w){this.app.Lc().D5(E,D,w)});
g.$U.prototype.D5=g.wQ(40,function(E,D,w){this.S.D5(E,D,w)});
g.MK.prototype.D5=g.wQ(39,function(E,D,w){if(this.TZ!==E||this.KC!==D)D=D==="rawcc"?"":D,w=[E,D,this.TZ,w],g.i9(this,g.pA(this.provider),"cfs",w),this.TZ=E,this.KC=D});
g.jc.prototype.D5=g.wQ(38,function(E,D,w){this.qoe&&this.qoe.D5(E,D,w)});
g.X_.prototype.D5=g.wQ(37,function(E,D,w){this.Te.D5(E,D,w)});
g.gu.prototype.D5=g.wQ(36,function(){});
g.vn.prototype.D5=g.wQ(35,function(E,D,w){g.jS(this,36,[E,D,w])});
g.sC.prototype.j8=g.wQ(11,function(){return this.SE});
g.bS.prototype.j8=g.wQ(10,function(){return this.Lc().D4()});
g.E2.prototype.D4=g.wQ(9,function(){return this.app.j8()});
g.$U.prototype.D4=g.wQ(8,function(){return this.S.D4()});
g.X_.prototype.D4=g.wQ(7,function(){return this.loader?.j8()||null});
g.gu.prototype.D4=g.wQ(6,function(){return null});
g.vn.prototype.D4=g.wQ(5,function(){return null});
g.lV.prototype.y_=g.wQ(3,function(E){return(E=this.D(E))?E.Y:0});
g.iV.prototype.y_=g.wQ(2,function(){return 0});
var c9R=/#(.)(.)(.)/,OyX=/^#(?:[0-9a-f]{3}){1,2}$/i,NhI=class{constructor(){this.D=[];this.A=[]}Y(E){return E?this.A.concat(this.D):this.A}},Se=class extends g.sB{constructor(E){super();this.JT=E;this.Y=new NhI;this.eQ=new NhI;this.C=null;this.B=[];this.NR=[]}G(){}N(){}D(){}Z(){return""}zZ(){return!1}hi(E,D){if(this.JT.L().X("html5_dispatch_tracklist_loaded_event")){this.C&&(this.C.reject(),this.C=null);var w=[];this.JT.Cc("trackListLoaded",this.Y,w,D);this.JT.L().X("enable_po_decoration_of_forced_tracks")&&
this.JT.Cc("trackListLoaded",this.eQ,w,D);w.length?(D=new g.bv,D.promise.then(E.hi,()=>{}),this.C=D,Promise.all(w).then(D.resolve,D.reject).finally(()=>{this.C=null})):E.hi()}else E.hi()}I9(){this.C&&(this.C.reject(),this.C=null);
this.D();super.I9()}},yIQ={en:"English"},lBQ=class extends Se{constructor(E){super(E);this.A=new Set}N(E){var D=this.JT.Ez();if(D&&D.TH()){D=D.TH().textTracks;for(let w of D)w.kind==="subtitles"&&!this.A.has(w.language)&&w.language&&(gS(this.Y,new g.nJ({languageCode:w.language,languageName:w.language,kind:w.kind,id:w.id,displayName:yIQ[w.label]||w.label,vss_id:`.${w.language}`})),this.A.add(w.language))}this.Y.Y().length>0&&E.hi()}},U40=class extends Se{constructor(E,D,w){super(E);this.videoData=
D;this.audioTrack=w;this.A=null;this.U=!1;this.B=D.bZ;this.NR=D.Je;this.U=g.Jx(D)}G(E,D,w){this.hT();D=this.Z(E,D);var h=this.JT.L().X("html5_report_captions_ctmp_qoe"),d=(0,g.X)();this.D();mML(this,D,{format:"RAW",onSuccess:a=>{this.A=null;if(h){var P=(a.responseText.length/1024).toFixed();let S=(0,g.X)();this.videoData.W("capresp",{ms:S-d,kb:P})}P=a.getResponseHeader&&a.getResponseHeader("Content-Length")?Number(a.getResponseHeader("Content-Length")):0;w.X8(a.responseText,E,void 0,void 0,P)},
onError:h?a=>{this.videoData.W("capfail",{status:a?.status??0})}:void 0,
withCredentials:!0})}N(E){if(this.audioTrack){for(let D of this.audioTrack.captionTracks)gS(this.Y,D);this.audioTrack.Y&&gS(this.eQ,this.audioTrack.Y)}this.hi(E,this.videoData.videoId)}Z(E,D){var w=E.hD(),h={fmt:D};if(D==="srv3"||D==="3"||D==="json3")g.RK()?Object.assign(h,{xorb:2,xobt:1,xovt:1}):Object.assign(h,{xorb:2,xobt:3,xovt:3});E.translationLanguage&&(h.tlang=g.kI(E));this.U&&(h.xosf="1");Object.assign(h,this.JT.L().Y);return g.R8(w,h)}D(){this.A&&this.A.abort()}},iBc=class{constructor(){this.segments=
[]}contains(E){E=g.KG(this.segments,E);return E>=0||E<0&&(-E-1)%2===1}length(){return this.segments.length/2}},JIM=class extends g.sB{constructor(E,D,w,h,d,a){super();this.policy=E;this.player=D;this.wi=w;this.U=h;this.C=d;this.Y9=a;this.N=new iBc;this.Z=-1;this.A=this.D=this.Y=null;this.NR=0;this.G=new g.H3(this.B,1E3,this);this.events=new g.JE(this);g.N(this,this.G);g.N(this,this.events);this.events.O(D,"SEEK_COMPLETE",this.V);this.V();this.B()}I9(){super.I9();this.A&&this.A.cancel()}V(){this.seekTo(this.player.getCurrentTime())}seekTo(E){E-=
this.player.Xc();var D=this.Y;this.Y=g.rH(this.wi.G(E).x9);D!==this.Y&&this.Y9&&this.Y9()}reset(){this.N=new iBc;this.Z=-1;this.A&&(this.A.cancel(),this.A=null)}B(){this.hT();var E;if(E=this.Y!=null)E=this.Y,E=E.wi.N(E);if(E&&!this.A&&!(this.Y&&this.Y.segmentStartTime-this.player.getCurrentTime()>30)){E=this.Y;E=E.wi.qR(E);let d=E.x9[0];if(this.player.getVideoData()?.enableServerStitchedDai){var D=this.player.D4();if(D){var w=d.wi.info.id;let a=d.Ea;var h=E.x9[0].N;if(this.policy.GZ){if(D=g.SlR(D,
h,a,w,3))E.N=D}else if(w=D.wu(h,a,w,3))if(h=2,D.lA.has(a)?h=0:g.lA(D,a)&&(h=1),D=h,D===0)w&&(E.Y=new g.NB(w));else if(D===2){this.G.start();Zyc(this)&&this.seekTo(this.player.getCurrentTime());return}}}d.wi.index.Oh(d.Ea)?(this.N.contains(E.x9[0].Ea)||Qga(this,E),this.Y=g.rH(E.x9)):Zyc(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()}},pVR=class extends Se{constructor(E,D){super(D);this.A=E;this.K=D;this.U=null;this.V=!1;this.logger=new g.bR("caps");this.Y9=g.Fh(this.K,this.A)}G(E,
D,w){this.D();D=jg0(this,E.getId());D||(D=E.languageCode,D=this.A.isManifestless?LqX(this,D,"386"):LqX(this,D));if(D){var h=(D.index.y_(D.index.nY())-D.index.getStartTime(D.index.nY()))*1E3,d=new g.Ga7(this.K.L());this.U=new JIM(d,this.K,D,(a,P)=>{w.X8(a,E,P,h)},this.Y9||g.pu(D.info),()=>{this.U&&this.U.reset();
this.V=!0})}}zZ(){var E=this.V;
this.V=!1;return E}N(E){var D=this.K.L().X("html5_fallback_if_rawcc_missing");var w=this.A.Y.rawcc!=null;if(!this.Y9||!w&&D)D=this.A.isManifestless?A9c(this,"386"):A9c(this);else{if(!w){g.ov(this.logger,386248249,"rawcc used but unavailable");return}D=[new g.nJ({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.nJ({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let h of D)gS(this.Y,
h);E.hi()}D(){this.U&&(this.U.dispose(),this.U=null)}Z(){return""}},v1c=class extends Se{constructor(E,D,w,h,d,a){super(E);this.videoId=w;this.V=d;this.eventId=a;this.Y9={};this.A=null;E=h||g.o8(D).hl||"";E=E.split("_").join("-");this.U=g.R8(D,{hl:E})}G(E,D,w){this.hT();D=this.Z(E,D);this.D();this.A=g.Kq(D,{format:"RAW",onSuccess:h=>{this.A=null;var d=h.getResponseHeader&&h.getResponseHeader("Content-Length")?Number(h.getResponseHeader("Content-Length")):0;w.X8(h.responseText,E,void 0,void 0,d)},
withCredentials:!0})}N(E){var D=this.U,w={type:"list",tlangs:1,v:this.videoId,vssids:1};this.V&&(w.asrs=1);D=g.R8(D,w);this.D();this.A=g.Kq(D,{format:"RAW",onSuccess:h=>{this.A=null;if((h=h.responseXML)&&h.firstChild){var d=h.getElementsByTagName("track");for(var a=0;a<d.length;a++){var P=d[a],S=P.getAttribute("lang_code");let K=P.getAttribute("lang_translated"),f=P.getAttribute("name"),m=P.getAttribute("kind"),M=P.getAttribute("id"),L=P.getAttribute("lang_default")==="true",A=P.getAttribute("cantran")===
"true";P=P.getAttribute("vss_id");gS(this.Y,new g.nJ({languageCode:S,languageName:K,name:f,kind:m,id:M,is_servable:!0,is_translateable:A,vss_id:P,is_default:L}))}h=h.getElementsByTagName("target");d=h.length;for(a=0;a<d;a++)S={languageCode:h[a].getAttribute("lang_code"),languageName:h[a].getAttribute("lang_translated"),languageOriginal:h[a].getAttribute("lang_original"),id:h[a].getAttribute("id"),isDefault:h[a].getAttribute("lang_default")==="true"},this.Y9[S.languageCode]=S.languageName,this.B.push(S)}this.hi(E,
this.videoId)},
withCredentials:!0})}Z(E,D){var w=this.U;D={v:this.videoId,type:"track",lang:E.languageCode,name:E.getName(),kind:E.kind,fmt:D};var h=this.JT.L();h.X("captions_url_add_ei")&&(D.ei=this.eventId);E.translationLanguage&&(D.tlang=g.kI(E));Object.assign(D,h.Y);return w=g.R8(w,D)}D(){this.A&&this.A.abort()}},U4=/^#(?:[0-9a-f]{3}){1,2}$/i;var XVI=["left","right","center","justify"];var of=class extends g.h4{constructor(E,D,w,h,d,a=!1,P=null){super(E,E+D,{priority:w,namespace:"captions"});this.windowId=h;this.text=d;this.append=a;this.Y=P}toString(){return super.toString()}};var PI=class extends g.ci{constructor(E,D,w,h,d,a,P,S,K,f){var m=f.isInline()&&!0,M={};Object.assign(M,D);Object.assign(M,E.params);Object.assign(M,w);var L={};Object.assign(L,D.ll);E.params.ll&&Object.assign(L,E.params.ll);Object.assign(L,w.ll);m&&(M.windowOpacity=.6,L.backgroundOpacity=0);M.ll=L;var A=M.sF===1,Y=[{j:"span",Dn:"captions-text",di:{style:"word-wrap: normal; display: block;"}}],b=S.tT("caption_edit_on_hover")&&f.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
b&&Y.unshift({j:"button",Dn:"caption-edit",di:{tabindex:"0","aria-label":f50()},yC:[{j:"svg",di:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},yC:[{j:"path",di:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({j:"div",Dn:"caption-window",di:{id:`caption-window-${E.id}`,dir:A?"rtl":"ltr",tabindex:"0",lang:M.lang},yC:Y});
this.experiments=S;this.B=[];this.qR=!1;this.D=E;this.gi=this.jQ=null;this.Cg=a;this.g1=P;this.G=null;this.maxWidth=a*.96;this.maxHeight=P*.96;this.Y=M;this.ta=w;this.zZ=D;this.C=this.QC("captions-text");E=this.C.style;this.TZ=S.tT("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in E||"WebkitBoxDecorationBreak"in E);this.Kc=CTo(h,d,a,P);this.WW=K;b&&(this.U=this.QC("caption-edit"),this.O(this.U,"click",()=>{this.WW()}));
this.type=0;this.YF=this.Kc*qm$(L);this.Vg=m;this.Oa=S.tT("enable_centered_caption_for_tvfilm_video")&&f.getVideoData().isTvfilmVideo;this.Y9=f.L().m0().Y.a9(g.wq0);h=new g.AC(this.element,!0);g.N(this,h);h.subscribe("dragstart",this.Pn,this);h.subscribe("dragmove",this.F3,this);h.subscribe("dragend",this.U8,this);this.Wb=this.Qg=this.xF=this.qm=0;h="";this.Y.windowOpacity&&(h=qs(this.Y.windowColor),h="rgba("+h[0]+","+h[1]+","+h[2]+","+this.Y.windowOpacity+")");d={"background-color":h,display:this.Y.isVisible===
!1?"none":"","text-align":XVI[this.Y.textAlign]};this.TZ&&(d["border-radius"]=h?`${this.YF*.25}px`:"");(this.Z=this.D.params.sF===2||this.D.params.sF===3)&&Hy7(this,this.element);g.Pg(this.element,d);m&&this.element.parentElement?.style.setProperty("--caption-window-color",h);switch(this.Y.Ku){case 0:case 1:case 2:g.B3(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.B3(this.element,"ytp-caption-window-bottom")}}Pn(E,D){this.Qg=E;this.Wb=D;var w=g.Qa(this.element,this.element.parentElement);
this.qm=E-w.x;this.xF=D-w.y}F3(E,D){if(E!==this.Qg||D!==this.Wb){g.T6(this.element,"ytp-dragging")||g.B3(this.element,"ytp-dragging");var w=g.Cj(this.element);E=E-this.qm-.02*this.Cg;var h=D-this.xF-.02*this.g1,d=(E+w.width/2)/this.maxWidth*3;d=Math.floor(g.uL(d,0,2));var a=(h+w.height/2)/this.maxHeight*3;a=Math.floor(g.uL(a,0,2));D=d+a*3;E=(E+d/2*w.width)/this.maxWidth;E=g.uL(E,0,1)*100;w=(h+a/2*w.height)/this.maxHeight;w=g.uL(w,0,1)*100;this.D.params.Ku=D;this.D.params.mI=w;this.D.params.nh=E;this.D.params.isDefault=
!1;this.Y.Ku=D;this.Y.mI=w;this.Y.nh=E;this.Y.isDefault=!1;this.zZ.Ku=D;this.zZ.mI=w;this.zZ.nh=E;this.zZ.isDefault=!1;this.Jy()}}U8(){g.oY(this.element,"ytp-dragging")}Jy(){this.V(this.B)}V(E){var D=this.Vg?0:Math.min(this.yf(),this.maxWidth),w=this.KC(),h=this.Vg;if(h){var d=getComputedStyle(this.C.parentNode);d=Yi(d.borderLeftWidth)+Yi(d.borderRightWidth)+Yi(d.paddingLeft)+Yi(d.paddingRight)}else d=0;var a=d;d="";this.D.params.sF===3&&(d="rotate(180deg)");var P=h?`calc(96% - ${a}px)`:"96%";g.Pg(this.element,
{top:0,left:0,right:"",bottom:"",width:D?`${D}px`:"",height:w?`${w}px`:"","max-width":P,"max-height":P,margin:"",transform:""});this.VC(E);d={transform:d,top:"",left:"",width:D?`${D}px`:"",height:w?`${w}px`:"","max-width":"","max-height":""};P=this.Y.Ku;var S=this.Y.nh,K=this.Y.mI;this.Oa&&P!=null&&(S=50,P=Math.floor(P/3)*3+1);S=S*.96+2;switch(P){case 0:case 3:case 6:(h=this.Y.ll.fontSizeIncrement)&&h>0&&this.Y.sF!==2&&this.Y.sF!==3&&(S=Math.max(S/(1+h*2),2));d.left=`${S}%`;break;case 1:case 4:case 7:d.left=
`${S}%`;S=0;this.Y9||(S=this.C.offsetWidth);D||S?(D=D||S+1,d.width=`${D}px`,d["margin-left"]=h?`${D/-2-a/2}px`:`${D/-2}px`):(this.Y9&&(d.width="max-content"),d.transform+=" translateX(-50%)");break;case 2:case 5:case 8:d.right=`${100-S}%`}h=K*.96+2;switch(P){case 0:case 1:case 2:d.top=`${h}%`;break;case 3:case 4:case 5:d.top=`${h}%`;h=0;this.Y9||(h=this.element.clientHeight);(w=w||h)?(d.height=`${w}px`,d["margin-top"]=`${w/-2}px`):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=
`${100-h}%`}g.Pg(this.element,d);this.U&&(this.Y9?w=this.YF:(E=xM7(this,E),w=this.Oa?E>0?this.C.offsetHeight/E:0:this.C.offsetHeight/E),this.U.style.height=`${w}px`,this.U.style.width=`${w}px`,this.element.style.paddingLeft=`${w+5}px`,this.element.style.paddingRight=`${w+5}px`,this.Y9||(E=Number(this.element.style.marginLeft.replace("px",""))-w-5,w=Number(this.element.style.marginRight.replace("px",""))-w-5,this.element.style.marginLeft=`${E}px`,this.element.style.marginRight=`${w}px`))}VC(E){if(this.type===
0&&this.D.params.gh!==void 0&&this.experiments.tT("web_enable_popon_asr_captions")){var D=E,w=this.D.params.gh;if(D.length===0||w<=0)E=[];else{E=[];for(let d=D.length-1;d>=0;d--){var h=D[d];E.unshift(h);let a=xM7(this,E);if(a>w){E.shift();typeof h.text==="string"&&(D=h.text.split("\n"),w=a-w,D.length-w>0&&(w=D.slice(w),h=new of(h.start,h.end-h.start,h.priority||0,h.windowId,w.join("\n"),h.append,h.Y),E.unshift(h)));break}}}}for(h=0;h<E.length&&E[h]===this.B[h];h++);if(this.qR||this.B.length>h)h=0,
this.qR=!1,this.B=[],this.G=this.gi=this.jQ=null,g.uO(this.C);for(;h<E.length;h++)Wq0(this,E[h])}yf(){return 0}KC(){return 0}toString(){return super.toString()}};var uVQ=class{constructor(){this.D=this.time=this.mode=this.A=0;this.N=new $4a(this);this.C=new $4a(this);this.Y=[];this.clear()}clear(){this.D=this.time=this.mode=0;this.Y=[];this.reset()}reset(){this.mode=0;this.N.reset(0);this.C.reset(1)}},TtL=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],n1X=class{constructor(){this.type=0}set(E){this.type=E}get(){return this.type}},Gz0=class{constructor(){this.state=this.t5=this.sW=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}xD(){return this.state!==0}matches(E,D){return this.xD()&&E===this.sW&&D===this.t5}},t6X=class{constructor(){this.timestamp=this.Y=0}reset(){this.timestamp=
this.Y=0}},Ko=class{constructor(E){this.C=E;this.D=[];this.Y=this.A=this.row=0;this.style=new n1X;this.N=0;for(E=0;E<=15;E++){this.D[E]=[];for(let D=0;D<=32;D++)this.D[E][D]=new t6X}}updateTime(E){for(let D=1;D<=15;++D)for(let w=1;w<=32;++w)this.D[D][w].timestamp=E}debugString(){var E="\n";for(let D=1;D<=15;++D){for(let w=1;w<=32;++w){let h=this.D[D][w];E=h.Y===0?E+"_":E+String.fromCharCode(h.Y)}E+="\n"}return E}reset(E){for(let D=0;D<=15;D++)for(let w=0;w<=32;w++)this.D[D][w].reset();this.N=E;this.Y=
0;this.A=this.row=1}},FqR=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],RKo=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],NtR=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],y98=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],kzL=class{constructor(E){this.D=E;this.C=0;this.style=new n1X;this.Z=new Ko(this.D);this.G=new Ko(this.D);this.text=new Ko(this.D);this.A=this.Z;this.N=this.G;this.Y=this.A}reset(E,D){this.C=D;this.style.set(2);this.A=this.Z;this.N=this.G;this.Y=this.A;var w=(E<<2)+(D<<1);this.Z.reset(w);this.G.reset(w);this.text.reset((E<<
2)+(D<<1)+1)}},$4a=class{constructor(E){this.Y=E;this.C=0;this.D=new kzL(this.Y);this.Z=new kzL(this.Y);this.A=new Gz0;this.N=this.D}reset(E){this.C=E;this.A.clear();this.N=this.D;this.D.reset(E,0);this.Z.reset(E,1)}};var sq7=class{N(){}};var V4=class extends g.sB{reset(){}};var Rf=class extends g.h4{constructor(E,D,w,h,d){super(E,E+D,{priority:w,namespace:"captions"});this.id=h;this.params=d;this.Y=[]}toString(){return super.toString()}},Fn=0;var e5X=class extends V4{constructor(E){super();this.N=E;this.pens={};this.U={};this.B={};this.C="_"+Fn++;this.G={};this.A=this.Y=null;this.Z=!0}reset(){this.G={};this.A=this.Y=null;this.Z=!0}D(E,D){E=E.firstChild;E.getAttribute("format");D=D||0;Number.isFinite(D);E=Array.from(E.childNodes);for(var w of E)if(w.nodeType===1)switch(w.tagName){case "head":var h=w;break;case "body":var d=w}if(h){h=Array.from(h.childNodes);for(var a of h)if(a.nodeType===1)switch(a.tagName){case "pen":w=a.getAttribute("id");
h=this.pens;E={};var P=a.getAttribute("p");P&&Object.assign(E,this.pens[P]);P=y6(a,"b");P!=null&&(E.bold=P);P=y6(a,"i");P!=null&&(E.italic=P);P=y6(a,"u");P!=null&&(E.underline=P);P=l6(a,"et");P!=null&&(E.charEdgeStyle=P);P=l6(a,"of");P!=null&&(E.offset=P);P=i6(a,"bc");P!=null&&(E.background=P);P=i6(a,"ec");P!=null&&(E.j_=P);P=i6(a,"fc");P!=null&&(E.color=P);P=l6(a,"fs");P!=null&&P!==0&&(E.fontFamily=P);P=Ns(a,"sz");P!==void 0&&(E.fontSizeIncrement=P/100-1);P=Ns(a,"bo");P!==void 0&&(E.backgroundOpacity=
P/255);P=Ns(a,"fo");P!==void 0&&(E.textOpacity=P/255);P=l6(a,"rb");P!=null&&P!==10&&P!==0&&(E.L6=P>10?P-1:P);P=l6(a,"hg");P!=null&&(E.GV=P);h[w]=E;break;case "ws":h=a.getAttribute("id");this.B[h]=$MM(this,a);break;case "wp":h=a.getAttribute("id"),this.U[h]=ufR(this,a)}}if(d){a=[];d=Array.from(d.childNodes);for(b of d)if(b.nodeType===1)switch(b.tagName){case "w":this.Y=nvL(this,b,D,!1);(d=this.G[this.Y.id])&&d.end>this.Y.start&&(d.end=this.Y.start);this.G[this.Y.id]=this.Y;a.push(this.Y);break;case "p":var S=
b;E=D;d=[];h=S.getAttribute("w")||this.C;w=!!y6(S,"a");E=(Ns(S,"t")||0)+E;P=Ns(S,"d")||5E3;w||(!this.Z&&this.A&&this.A.windowId===h&&this.A.end>E&&(this.A.end=E),this.A&&this.A.text==="\n"&&(this.A.text=""));let U=w?6:5;var K=S.getAttribute("p");K=K?this.pens[K]:null;let l=Array.from(S.childNodes);l.length&&(this.Z=S.getAttribute("d")!=null);for(S=0;S<l.length;S++){var f=l[S],m=void 0;S>0&&(w=!0);let p;f.nodeType===1&&(p=f);if(p&&p.tagName==="s"){if((f=(f=p.getAttribute("p"))?this.pens[f]:null)&&
f.L6&&(f.L6===1?(f=l.slice(S,S+4),f.length===4&&(m=vvL(E,P,h,w,U,f,this.pens),S+=3)):m=vvL(E,P,h,w,U,[p],this.pens)),!m){var M=p;m=E;f=P;var L=h,A=w;let G=M.textContent?M.textContent:"";var Y=M.getAttribute("p");Y=Y?this.pens[Y]:null;M=Ns(M,"t")||0;m=new of(m+M,f-M,U,L,G,A,Y)}}else m=new of(E,P,U,h,f.textContent||"",w,K);d.push(m);this.A=m}if(d.length>0){d[0].windowId===this.C&&(this.Y=nvL(this,b,D,!0),a.push(this.Y));for(let p of d)p.windowId=this.Y.id,this.Y.Y.push(p),a.push(p)}}var b=a}else b=
[];return b}};var Ea8=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),DTL=class extends V4{constructor(E){super();this.Z=E;this.Y=new Map;this.N=new Map;this.C=new Map;this.A=new Map}reset(){this.A.clear()}D(E,D){E=JSON.parse(E);if(!E)return[];if(E.pens){var w=E.pens,h=0;for(var d of w){w={};var a=d.pParentId;a&&Object.assign(w,this.Y.get(a));d.bAttr&&(w.bold=!0);d.iAttr&&(w.italic=!0);d.uAttr&&(w.underline=!0);a=d.ofOffset;a!=null&&(w.offset=a);d.szPenSize!==void 0&&(w.fontSizeIncrement=d.szPenSize/100-1);
a=d.etEdgeType;a!=null&&(w.charEdgeStyle=a);d.ecEdgeColor!==void 0&&(w.j_=J8(d.ecEdgeColor));a=d.fsFontStyle;a!=null&&a!==0&&(w.fontFamily=a);d.fcForeColor!==void 0&&(w.color=J8(d.fcForeColor));d.foForeAlpha!==void 0&&(w.textOpacity=d.foForeAlpha/255);d.bcBackColor!==void 0&&(w.background=J8(d.bcBackColor));d.boBackAlpha!==void 0&&(w.backgroundOpacity=d.boBackAlpha/255);(a=d.rbRuby)&&a!==10&&(w.L6=a>10?a-1:a,w.textEmphasis=Ea8.get(w.L6));d.hgHorizGroup&&(w.GV=d.hgHorizGroup);this.Y.set(h++,w)}}if(E.wsWinStyles){h=
E.wsWinStyles;d=0;for(var P of h)h={},(w=P.wsParentId)?Object.assign(h,this.C.get(w)):Object.assign(h,this.Z),P.mhModeHint!==void 0&&(h.oL=P.mhModeHint),P.juJustifCode!==void 0&&(h.textAlign=P.juJustifCode),P.pdPrintDir!==void 0&&(h.sF=P.pdPrintDir),P.sdScrollDir!==void 0&&(h.J6=P.sdScrollDir),P.wfcWinFillColor!==void 0&&(h.windowColor=J8(P.wfcWinFillColor)),P.wfoWinFillAlpha!==void 0&&(h.windowOpacity=P.wfoWinFillAlpha/255),this.C.set(d++,h)}if(E.wpWinPositions){d=E.wpWinPositions;P=0;for(var S of d)d=
{},(h=S.wpParentId)&&Object.assign(d,this.N.get(h)),S.ahHorPos!==void 0&&(d.nh=S.ahHorPos),S.apPoint!==void 0&&(d.Ku=S.apPoint),S.avVerPos!==void 0&&(d.mI=S.avVerPos),S.ccCols!==void 0&&(d.V6=S.ccCols),S.rcRows!==void 0&&(d.gh=S.rcRows),this.N.set(P++,d)}if(E.events){E=E.events;S=[];for(let k of E)if(P=(k.tStartMs||0)+D,d=k.dDurationMs||0,k.id)h=String(k.id),E=Gha(this,k,P,d,h),S.push(E),this.A.set(h,E);else{k.wWinId?h=k.wWinId.toString():(h="_"+Fn++,E=Gha(this,k,P,d,h),S.push(E),this.A.set(h,E));
E=S;var K=k;d===0&&(d=5E3);w=this.A.get(h);let S7=(a=!!K.aAppend)?6:5,f8=K.segs,qa=null;K.pPenId&&(qa=this.Y.get(K.pPenId));for(K=0;K<f8.length;K++){var f=f8[K],m=f.utf8;if(m){var M=f.tOffsetMs||0;let TM=null;f.pPenId&&(TM=this.Y.get(f.pPenId));if((w.params.oL!=null?w.params.oL:w.Y.length>1?1:0)===2&&a&&m==="\n")continue;f=null;var L=[],A;if(A=TM&&TM.L6===1)a:{A=f8;var Y=K;if(Y+3>=A.length||!A[Y+1].pPenId||!A[Y+2].pPenId||!A[Y+3].pPenId){A=!1;break a}var b=A[Y+1].pPenId;(b=this.Y.get(b))&&b.L6&&b.L6===
2?(b=A[Y+2].pPenId,b=this.Y.get(b),!b||!b.L6||b.L6<3?A=!1:(b=A[Y+3].pPenId,A=(b=this.Y.get(b))&&b.L6&&b.L6===2?!0:!1)):A=!1}if(A)M=f8[K+1].utf8,f=f8[K+3].utf8,A=f8[K+2].utf8,Y=this.Y.get(f8[K+2].pPenId),m=p90(m,M,A,f,Y),f=new of(P,d,S7,h,m,a,TM),K+=3;else{if(m.indexOf("<")>-1){L=TM;A=qa;Y=P;b=d;var U=M,l=S7,p=a;let n8=[];var G=xi(`<html>${m}</html>`);if(!G.getElementsByTagName("parsererror").length&&G.firstChild?.childNodes.length)for(let u0 of G.firstChild.childNodes){G=u0.textContent?.replace(/\n/g,
"")??"";if(u0.nodeType===3&&(!G||G.match(/^ *$/)!=null))continue;let iG={};Object.assign(iG,L||A);switch(u0?.tagName){case "b":iG.bold=!0;break;case "i":iG.italic=!0;break;case "u":iG.underline=!0}n8.push(new of(Y+U,b-U,l,w.id,G,p,iG))}L=n8}L.length||(L=[new of(P+M,d-M,S7,w.id,m,a,TM||qa)])}if(L.length)for(let n8 of L)E.push(n8),w.Y.push(n8);else f&&(E.push(f),w.Y.push(f))}a=!0}}D=S}else D=[];return D}};var MXc=class extends Se{constructor(E,D,w){super(E);this.videoData=D;this.audioTrack=w;this.B=D.bZ}G(E,D,w){V07(this.videoData.videoId,E.vssId,w.X8)}N(E){if(this.audioTrack)for(let D of this.audioTrack.captionTracks)gS(this.Y,D);E.hi()}};var o1$=class extends PI{constructor(E,D,w,h,d,a,P,S,K,f){super(E,D,w,h,d,a,P,S,K,f);this.type=1}VC(E){var D=this.D.Y;super.VC(E);for(E=E.length;E<D.length;E++){let d=D[E],a;if(h&&d.Y===w)a=h;else{a={};Object.assign(a,d.Y);Object.assign(a,ZgR);var w=d.Y;var h=a}Wq0(this,d,a)}}},ZgR={I8:!0};var t0c=class extends sq7{constructor(E,D){super();this.trackData=E;this.Z=D;this.version=this.C=this.D=this.byteOffset=0;this.A=[];this.Y=new DataView(this.trackData)}N(E,D,w,h,d){if(w<h){let a="_"+Fn++;w=w/1E3-this.Z;h=h/1E3-this.Z;E=new Rf(w,h-w,5,a,{textAlign:0,Ku:0,nh:D*2.5,mI:E*5.33});d=new of(w,h-w,5,a,d);this.A.push(E);this.A.push(d)}}},QjX=class extends V4{constructor(E,D){super();this.A=E;this.N=D;this.track=this.N.languageName==="CC3"?4:0;this.Y=new uVQ;this.Y.A=1<<this.track}D(E){E=new t0c(E,
this.A);if(khc(E)){for(;E.byteOffset<E.Y.byteLength;)for(E.version===0?E.D=v4(E)*(1E3/45):E.version===1&&(E.D=v4(E)*4294967296+v4(E)),E.C=pi(E);E.C>0;E.C--){var D=pi(E);let w=pi(E),h=pi(E);D&4&&(D&3)===this.track&&(this.track===0||this.track===1)&&(D=this.Y,D.Y.push({time:E.D,type:this.track,kQ:w,MO:h,order:D.Y.length}))}ov8(this.Y,E);return E.A}return[]}reset(){this.Y.clear()}};var FB7=class extends PI{constructor(E,D,w,h,d,a,P,S,K,f){super(E,D,w,h,d,a,P,S,K,f);this.type=2;this.Ua=[];this.eQ=this.NR=this.sa=0;this.GZ=NaN;this.Sp=0;this.fM=null;this.Vf=new g.H3(this.ZB,433,this);this.U&&(f.createClientVe(this.U,this,167342),this.O(this.U,"click",()=>{f.logClick(this.U)}),E=new g.AC(this.element,!0),g.N(this,E),E.subscribe("hoverstart",()=>{f.logVisibility(this.U,!0)},this));
g.B3(this.element,"ytp-caption-window-rollup");g.N(this,this.Vf);g.Pg(this.element,"overflow","hidden")}Jy(){var E=this.Vf;E.stop();E.kf()}ZB(){this.element.removeEventListener("transitionend",this.ZB,!1);g.oY(this.element,"ytp-rollup-mode");this.V(this.fM,!0)}KC(){return this.Z?this.eQ:this.NR}yf(){return this.Z?this.NR:this.eQ}V(E,D){this.fM=E;if(this.D.params.gh){var w=0;for(let h=0;h<this.B.length&&w<E.length;h++)this.B[h]===E[w]&&w++;w>0&&w<E.length&&(E=this.B.concat(E.slice(w)));this.Sp=this.eQ;
this.NR=this.eQ=0;super.V(E);D4L(this,D)}super.V(E)}};var jj0=class{constructor(E,D,w,h){this.K=E;this.C=D;this.logger=w;this.At=h;this.Jt=[];this.Y=null;this.D=[];this.Gf=[];this.A=null;E=g.l7(this.K.L().experiments,"html5_override_micro_discontinuities_threshold_ms");this.N=E>0?E:10}unload(){this.A!=null&&(this.K.removeEventListener("sabrCaptionsDataLoaded",this.A),this.A=null);this.Jt=[];this.Y=null;this.D=[];this.K.Cc("sabrCaptionsBufferedRangesUpdated",this.Jt)}G(E){return{formatId:g.XP(E.info.wi.info,this.At),Ea:E.info.Ea+(this.At?0:1),startTimeMs:E.info.N*
1E3,durationMs:E.info.G*1E3}}};var L$L=class extends Se{constructor(E,D){super(D);this.A=E;this.K=D;this.logger=new g.bR("caps");this.U=this.Y9=null;this.V=new jj0(this.K,this,this.logger,this.A.At)}G(E,D,w){this.D();D=E.getId();D=D!=null&&D in this.A.Y?this.A.Y[D]:null;D||(D=E.languageCode,D=this.A.isManifestless?KBR(this,D,"386"):KBR(this,D));D&&(this.U=E,this.Y9=D,PlM(this.V,w),this.K.Cc("sabrCaptionsTrackChanged",g.XP(D.info,this.A.At)))}N(E){var D=this.A.isManifestless?V6Q(this,"386"):V6Q(this);for(let w of D)gS(this.Y,w);
E.hi()}D(){this.U&&(this.U=this.Y9=null,this.V.unload(),this.K.Cc("sabrCaptionsTrackChanged",null))}Z(){return""}};var OBR="WEBVTT".split("").map(E=>E.charCodeAt(0)),ZB$=class extends V4{constructor(){super()}D(E,D){E instanceof ArrayBuffer&&(E=g.CF(new Uint8Array(E)));
var w=[];E=E.split(A1I);for(let Y=1;Y<E.length;Y++){var h=E[Y],d=D;if(h!==""&&!Cd$.test(h)){var a=Oy.exec(h);if(a&&a.length>=4){var P=Xn(a[1]),S=Xn(a[2])-P;P+=d;var K=(a=a[3])?a.split(" "):[];a={};var f=null;var m="";var M=null,L="";for(let b of K){K=b.split(":");if(K.length!==2)continue;var A=K[1];switch(K[0]){case "line":K=A.split(",");K[0].endsWith("%")&&(f=K[0],a.mI=Number.parseInt(f,10),K.length===2&&(m=K[1].trim()));break;case "position":K=A.split(",");M=K[0];a.nh=Number.parseInt(M,10);K.length===
2&&(L=K[1].trim());break;case "align":switch(A){case "start":a.textAlign=0;break;case "middle":a.textAlign=2;break;case "end":a.textAlign=1}}}f||m||(m="end");if(!M)switch(a.textAlign){case 0:a.nh=0;break;case 1:a.nh=100;break;case 2:a.nh=50}if(a.textAlign!=null){f=0;switch(m){case "center":f+=3;break;case "end":f+=6;break;default:f+=0}switch(L){case "line-left":f+=0;break;case "center":f+=1;break;case "line-right":f+=2;break;default:switch(a.textAlign){case 0:f+=0;break;case 2:f+=1;break;case 1:f+=
2}}m=f<0||f>8?7:f;a.Ku=m}h=h.substring(Oy.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=a;a={};if(h.indexOf("<")<0&&h.indexOf("&")<0)d=fB7(P,S,5,L),P=new of(P,S,5,d.id,h,!1,g.mx(a)?void 0:a),w.push(d),w.push(P),d.Y.push(P);else for(m=h.split(qSo),m.length===1?(h=5,L=fB7(P,S,h,L)):(f=h=6,L=Object.assign({V6:32},L),L=new Rf(P,S,f,"_"+Fn++,L)),w.push(L),f=P,M=0;M<m.length;M++)if(K=m[M],M%2===0){A=xi(`<html>${K}</html>`);let b;A.getElementsByTagName("parsererror").length?(b=A.createElement("span"),
b.appendChild(A.createTextNode(K))):b=A.firstChild;z5L(this,f,S-(f-P),h,L,M>0,b,a,w)}else f=Xn(K)+d}Oy.lastIndex=0}}return w}},Cd$=/^NOTE/,A1I=/(?:\r\n|\r|\n){2,}/,Oy=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),qSo=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var HgX=class extends g.sB{constructor(E,D){super();this.K=E;this.J=D;this.Y=null;this.SE=this.K.D4();this.logger=new g.bR("caps")}clear(){this.Y&&this.Y.dispose();this.Y=null}reset(){this.Y&&this.Y.reset()}I9(){super.I9();this.clear()}};var ClI={windowColor:"#080808",windowOpacity:0,textAlign:2,Ku:7,nh:50,mI:100,isDefault:!0,ll:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},AIR={windowColor:"#080808",windowOpacity:0,textAlign:0,Ku:7,nh:50,mI:100,isDefault:!0,ll:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.oy("captions",class extends g.qK{constructor(E){super(E);this.K=E;this.Ua=[];this.eQ={};this.gi={};this.U=!1;this.D="NONE";this.Y=this.B=this.V=this.vX=this.Kc=null;this.dI={hi:()=>{this.hi()},
X8:(h,d,a,P,S=0)=>{var K=Number(this.videoData.L().m0().Y.a9(g.zn8)??0);S>0&&K>0&&this.videoData.lengthSeconds>0&&S/this.videoData.lengthSeconds>K?this.K.W("tts",{dropcap:S}):this.X8(h,d,a,P)}};
this.TZ=this.A=null;this.J=this.K.L();this.videoData=this.K.getVideoData();this.ZB=this.K.l2();this.C={ll:{}};this.Z={ll:{}};g.DV(this.videoData)?this.D="OFFLINE":g.klM(this.videoData,this.K)?this.D="HLS":SdQ(this.videoData,this.K)?this.D="SABR_LIVE":g.sC0(this.videoData,this.K)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.xF&&(this.D="TTS");this.qR=this.J.controlsType==="3";this.sa=new HgX(this.K,this.J);this.zZ=new g.JE(this);this.G=new g.ci({j:"div",Dn:"ytp-caption-window-container",
di:{id:"ytp-caption-window-container"}});this.NR={top:0,right:0,bottom:0,left:0,width:1,height:1};var D=null,w=g.aO("yt-html5-player-modules::subtitlesModuleData");w&&(D=new g.uB(w));this.storage=D;D=E.Ez();this.Qg=!!D?.gi();this.Oa=!!D?.sa();this.N=$i(this);this.Y9=LB7(this);g.N(this,this.sa);this.N?this.jQ=this.GZ=null:(this.GZ=new g.Ar(this.qm,void 0,this),g.N(this,this.GZ),this.jQ=new g.H3(this.Sp,2E3,this),g.N(this,this.jQ));g.N(this,this.zZ);g.bk(this.player,this.G.element,4);g.N(this,this.G);
this.N||this.zZ.O(E,"resize",this.VC);D=g.vU(this.J)&&!g.m2()&&!this.K.isFullscreen();w=this.J.m0().Y.a9(g.F3M)&&g.hF(this.J)&&g.Xz;(this.Wb=(D||w)&&!this.N&&!this.Y9)&&this.zZ.O(E,D?"resize":"fullscreentoggled",this.Vg);this.zZ.O(E,"onPlaybackAudioChange",this.xF);this.zZ.O(E,g.EV("captions"),h=>{this.onCueRangeEnter(h)});
this.zZ.O(E,g.Dx("captions"),h=>{this.onCueRangeExit(h)});
u6(this,H4()||{});g.f6(this.player,"onCaptionsModuleAvailable");this.D==="HLS"&&this.N&&(E=this.K.Ez().TH(),this.Oa&&this.zZ.O(E.textTracks,"addtrack",this.KC))}I9(){if(this.N||this.Y9){let E=this.K.Ez();E&&!E.hT()&&E.U()}else ni(this,!1);super.I9()}gZ(){if(this.qR)return this.N||this.Y9;if(this.D==="HLS")return this.N;var E=this.getAudioTrack();if(Ydo(this)){if(!E.captionTracks.length)return!1;if(!this.Y)return!0}E=Ci(E,g.Hp(this.J));return E==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:E==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
s4(this):ki(this)||s4(this)?!0:x4$(this)}load(){super.load();this.B=this.getAudioTrack();if(this.Y)this.A&&(this.sa.clear(),this.N?IBa(this,!0):this.player.getPresentingPlayerType()!==3&&this.Y.G(this.A,"json3",this.dI),this.D!=="HLS"&&this.N||this.Y9||e9(this)||g.f6(this.player,"captionschanged",A8(this.A)));else{if(this.D==="OFFLINE")var E=new MXc(this.player,this.videoData,this.getAudioTrack());else this.D==="SABR_LIVE"?E=new L$L(this.videoData.Y,this.player):this.D==="HLS"?E=new lBQ(this.player):
this.D==="LIVE"?E=new pVR(this.videoData.Y,this.player):this.D==="INNERTUBE"?E=new U40(this.player,this.videoData,this.getAudioTrack()):(E=this.videoData,E=new v1c(this.player,this.videoData.xF,this.videoData.videoId,E.captionsLanguagePreference||E.AT.captionsLanguagePreference||g.bZ(E,"yt:cc_default_lang")||E.AT.qm,this.videoData.J9,this.videoData.eventId));this.Y=E;g.N(this,this.Y);this.Y.N(this.dI)}}unload(){this.N&&this.A?IBa(this,!1):(this.jQ&&this.jQ.MF(),this.player.YE("captions"),this.Ua=
[],this.Y&&this.Y.D(),this.sa.clear(),this.V&&this.player.kE(this.V),this.VC());super.unload();this.player.om();g.f6(this.player,"captionschanged",{})}create(){this.gZ()&&this.load();var E;a:{if(this.J.X("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(E=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let D of E)if(D.kind==="asr"&&D.languageCode==="en"){E=
!0;break a}E=!1}E&&this.K.Cc("showpromotooltip",this.G.element)}hi(){var E=Ci(this.player.getAudioTrack(),g.Hp(this.J));var D=E==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?De(this,this.U):E==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&s4(this)?Ey(this):ki(this)||this.U||x4$(this)?De(this,this.U):s4(this)?Ey(this):null;if(this.D!=="HLS"&&this.N||this.Y9){let w=this.Y.Y.Y(!0);E=[];for(let h=0;h<w.length;h++){let d=w[h],a=g.X$("TRACK");a.setAttribute("kind","subtitles");a.setAttribute("label",g.tD(d));a.setAttribute("srclang",
g.kI(d));a.setAttribute("id",d.toString());this.Y9||a.setAttribute("src",this.Y.Z(d,"vtt"));d===D&&a.setAttribute("default","1");E.push(a)}D=this.K.Ez();D.NR(E);E=D.TH();this.Oa&&this.zZ.O(E.textTracks,"change",this.Bx)}else!this.A&&D&&a3(this,D),g.f6(this.player,"onCaptionsTrackListChanged"),g.zW(this.player,"onApiChange")}getTrackById(E){var D=this.Y.Y.Y(!0);for(let w=0;w<D.length;w++)if(D[w].toString()===E)return D[w];return null}Bx(){var E=this.K.Ez().TH().textTracks,D=null;for(let w=0;w<E.length;w++)E[w].mode===
"showing"&&(D=this.getTrackById(E[w].id));(this.loaded?this.A:null)!==D&&a3(this,D,!0)}KC(){this.Y?.N(this.dI)}iT(){!this.A&&this.N||this.unload()}X8(E,D,w,h){if(E){dE(this,this.A??void 0);this.Y.zZ()&&(this.Ua=[],this.K.YE("captions"),Li(this.GZ),this.sa.reset());a:{var d=this.sa;h=h||0;w=M67(d,E,w||0);E=[];try{for(let l of w){let p=l.trackData,G=l.AA,k=d.J.X("safari_live_drm_captions_fix");if(typeof p!=="string"){w=E;var a=w.concat;if(k&&cI$(p))var P=QqR(d,p,G);else{var S=d,K=D,f=p,m=G,M=h;if(!sgo(f))throw Error("Invalid binary caption track data");
S.Y||(S.Y=new QjX(M,K));P=S.Y.D(f,m)}var L=a.call(w,P)}else{if(p.substring(0,6)==="WEBVTT")var A=E.concat(QqR(d,p,G));else{w=E;var Y=w.concat;b:{K=d;S=D;if(p[0]==="{")try{K.Y||(K.Y=new DTL(jqX(S)));var b=K.Y.D(p,G);break b}catch(qa){g.VD(qa);b=[];break b}let S7=xi(p);if(!S7||!S7.firstChild){let qa=Error("Invalid caption track data");qa.params=p;throw qa;}if(S7.firstChild.tagName==="timedtext"){if(Number(S7.firstChild.getAttribute("format"))===3){f=S7;K.Y||(K.Y=new e5X(jqX(S)));b=K.Y.D(f,G);break b}let qa=
Error("Unsupported subtitles format in web player (Format2)");qa.params=p;throw qa;}if(S7.firstChild.tagName==="transcript"){let qa=Error("Unsupported subtitles format in web player (Format1)");qa.params=p;throw qa;}let f8=Error("Invalid caption track data");f8.params=p;throw f8;}A=Y.call(w,b)}L=A}E=L}var U=E;break a}catch(l){g.ov(d.logger,187101178,`Captions parsing failed: ${l.message}. `);d.clear();U=[];break a}U=void 0}this.J.X("html5_sabr_live_support_subfragmented_captions")&&this.Y instanceof
L$L&&(D=this.Y.V,d=[],U.length>0&&(d=U.slice(D.D.length)),D.D=!D.Y||D.Y.info.KM?[]:U,U=d);U.length>0&&(D=this.A,this.D5(D,!!D,e9(this)?"g":this.U?"m":"s"));this.player.kE(U,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");!this.U||this.Y9||e9(this)||g.Q2(this.J)||g.mi(this.J)||g.Sa(this.J)||this.J.U==="shortspage"||this.player.isInline()||(this.jQ.MF(),U=X97({Ku:0,nh:5,mI:5,gh:2,textAlign:0,sF:0,lang:"en"}),this.vX=[U],D=["Click "," for settings"],this.Kc||(d=new g.Da({j:"svg",di:{height:"100%",version:"1.1",
viewBox:"0 0 36 36",width:"100%"},yC:[{j:"path",H9:!0,di:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.N(this,d),this.Kc=d.element),d=U.end-U.start,(L=g.tD(this.A))&&this.vX.push(new of(U.start,d,0,U.id,L)),this.vX.push(new of(U.start,d,0,U.id,D[0]),new of(U.start,d,0,U.id,this.Kc,!0),new of(U.start,d,0,U.id,D[1],!0)),this.player.kE(this.vX),g.gU(this.jQ));!this.U||this.Y9||e9(this)||(this.J.X("enable_player_captions_persistence_state_machine")?t8(this,!0):g.Hp(this.J)?wE(this,!0):hY(this,!0),this.B&&(this.B.N=this.A),this.player.om());this.U=!1}}onCueRangeEnter(E){this.Ua.push(E);
Li(this.GZ)}onCueRangeExit(E){g.EB(this.Ua,E);this.Y instanceof pVR&&this.Y.Y9&&this.player.lx([E]);Li(this.GZ)}getCaptionWindowContainerId(){return this.G.element.id}Sp(){qdX(this,this.vX);this.vX=null}qm(){if(!this.Wb||!this.N){this.GZ.stop();g.M_(this.gi);this.Ua.sort(g.em);var E=this.Ua;if(this.V){let D=g.ok(E,function(w){return this.V.indexOf(w)===-1},this);
D.length&&(E=D)}for(let D of E)D instanceof Rf?rII(this,D):Bh0(this,D);for(let [D,w]of Object.entries(this.eQ)){let h=D,d=w;this.gi[h]?(d.element.parentNode||(d instanceof FB7||d instanceof o1$||g.dd(this.eQ,(a,P)=>{P!==h&&a.D.params.Ku===d.D.params.Ku&&a.D.params.nh===d.D.params.nh&&a.D.params.mI===d.D.params.mI&&(a.dispose(),delete this.eQ[P]);return P===h},this),this.G.element.appendChild(d.element)),d.V(this.gi[h])):(d.dispose(),delete this.eQ[h])}}}qG(){u6(this,{},!0);
g.f6(this.player,"captionssettingschanged")}KU(){var E=this.J.X("enable_player_captions_new_style_defaults")?AIR:ClI,D=E.ll;E={background:D.background,backgroundOpacity:D.backgroundOpacity,charEdgeStyle:D.charEdgeStyle,color:D.color,fontFamily:D.fontFamily,fontSizeIncrement:D.fontSizeIncrement,fontStyle:D.bold&&D.italic?3:D.bold?1:D.italic?2:0,textOpacity:D.textOpacity,windowColor:E.windowColor,windowOpacity:E.windowOpacity};D=H4()||{};D.background!=null&&(E.background=D.background);D.backgroundOverride!=
null&&(E.backgroundOverride=D.backgroundOverride);D.backgroundOpacity!=null&&(E.backgroundOpacity=D.backgroundOpacity);D.backgroundOpacityOverride!=null&&(E.backgroundOpacityOverride=D.backgroundOpacityOverride);D.charEdgeStyle!=null&&(E.charEdgeStyle=D.charEdgeStyle);D.charEdgeStyleOverride!=null&&(E.charEdgeStyleOverride=D.charEdgeStyleOverride);D.color!=null&&(E.color=D.color);D.colorOverride!=null&&(E.colorOverride=D.colorOverride);D.fontFamily!=null&&(E.fontFamily=D.fontFamily);D.fontFamilyOverride!=
null&&(E.fontFamilyOverride=D.fontFamilyOverride);D.fontSizeIncrement!=null&&(E.fontSizeIncrement=D.fontSizeIncrement);D.fontSizeIncrementOverride!=null&&(E.fontSizeIncrementOverride=D.fontSizeIncrementOverride);D.fontStyle!=null&&(E.fontStyle=D.fontStyle);D.fontStyleOverride!=null&&(E.fontStyleOverride=D.fontStyleOverride);D.textOpacity!=null&&(E.textOpacity=D.textOpacity);D.textOpacityOverride!=null&&(E.textOpacityOverride=D.textOpacityOverride);D.windowColor!=null&&(E.windowColor=D.windowColor);
D.windowColorOverride!=null&&(E.windowColorOverride=D.windowColorOverride);D.windowOpacity!=null&&(E.windowOpacity=D.windowOpacity);D.windowOpacityOverride!=null&&(E.windowOpacityOverride=D.windowOpacityOverride);return E}mx(E,D){var w={};Object.assign(w,H4());Object.assign(w,E);u6(this,w,D);g.f6(this.player,"captionssettingschanged")}VC(){!this.N&&this.loaded&&(g.D_(this.eQ,function(E,D){E.dispose();delete this.eQ[D]},this),this.qm())}Cb(E,D){switch(E){case "fontSize":if(isNaN(D))break;
E=g.uL(D,-2,4);this.mx({fontSizeIncrement:E});return E;case "reload":D&&!this.N&&a3(this,this.A,!0);break;case "stickyLoading":D!==void 0&&this.J.G&&(this.J.X("enable_player_captions_persistence_state_machine")?t8(this,!(!D||!D.userInitiated)):g.Hp(this.J)?wE(this,!!D):hY(this,!!D));break;case "track":return R5$(this,D);case "tracklist":return this.Y?g.Ft(this.Y.Y.Y(!(!D||!D.includeAsr)),w=>A8(w)):[];
case "translationLanguages":return this.Y?this.Y.B.map(w=>Object.assign({},w)):[];
case "sampleSubtitles":this.N||D===void 0||ni(this,!!D);break;case "sampleSubtitlesCustomized":this.N||ni(this,!!D,D);break;case "recommendedTranslationLanguages":return g.Hq();case "defaultTranslationSourceTrackIndices":return this.Y?this.Y.NR:[]}}getOptions(){var E="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.J.G&&E.push("stickyLoading");return E}Qq(){var E=this.A;if(this.K.fY("captions")){if(this.J.X("html5_modify_caption_vss_logging"))return(E=this.videoData.k$??
null)?{cc:g.sT(E)}:{};if(E){let D=E.vssId;E.translationLanguage&&D&&(D=`t${D}.${g.kI(E)}`);return{cc:D}}}return{}}Zz(E){this.isSubtitlesOn()?(this.J.X("enable_player_captions_persistence_state_machine")&&E?t8(this,!1):g.Hp(this.J)?wE(this,!1):hY(this,!1),dE(this),a3(this,null,!0)):this.IW(E)}IW(E){var D=e9(this)||!this.A?De(this,!0):this.A;D&&this.F7(D.vssId,"m");this.isSubtitlesOn()||a3(this,D,this.J.X("enable_player_captions_persistence_state_machine")?E:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.A&&!e9(this)}xF(){var E=e9(this);s4(this,E)?a3(this,this.getAudioTrack().Y,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),Ydo(this)&&(this.U=!1,this.A=null,this.Y&&(this.Y.dispose(),this.Y=null)),this.gZ()&&(E?a3(this,De(this,!1),!1):this.load()))}Ts(E){if(this.J.experiments.tT("web_enable_captions_set_target_container")&&E!==this.TZ){var D=this.G.element;D.parentNode&&g.Gp(D);(this.TZ=E)?(this.TZ.appendChild(D),D.style.position="absolute",D.style.bottom="0",D.style.left=
"0",D.style.width="100%",D.style.height="auto",D.style.top="auto"):(g.bk(this.player,D,4),D.style.position="absolute",D.style.bottom="auto",D.style.left="0",D.style.width="100%",D.style.height="100%",D.style.top="0");this.VC()}}ND(E){E&&(this.NR={top:E.top,right:E.right,bottom:E.bottom,left:E.left,width:1-E.left-E.right,height:1-E.top-E.bottom},this.G.element.style.top=`${this.NR.top*100}%`,this.G.element.style.left=`${this.NR.left*100}%`,this.G.element.style.width=`${this.NR.width*100}%`,this.G.element.style.height=
`${this.NR.height*100}%`,this.G.element.style.position="absolute",E=bB0(this))&&(this.G.element.style.width=`${E.width}px`,this.G.element.style.height=`${E.height}px`)}onVideoDataChange(E,D){E==="newdata"&&(this.videoData=D,this.loaded&&this.unload(),this.U=!1,this.A=null,this.Y&&(this.Y.dispose(),this.Y=null,g.f6(this.player,"captionschanged",{})),this.gZ()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Vg(){if(this.J.m0().Y.a9(g.F3M)){if(this.loaded&&this.unload(),this.qR=this.K.isFullscreen()||
this.J.controlsType==="3",this.N=$i(this),this.Y9=LB7(this),this.N||this.Y9){var E=this.K.Ez();E&&!E.hT()&&E.U();this.hi()}}else(E=this.K.Ez())&&!E.hT()&&E.U(),this.K.isFullscreen()?(this.N=this.qR=!0,this.loaded&&this.hi()):(this.qR=this.J.controlsType==="3",this.N=$i(this));a3(this,this.A)}YF(){var E=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;E&&g.cZ(this.player,"innertubeCommand",E)}D5(E,D,w){var h=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,d="";E&&
(d=E.vssId,d=d.replace(h,""));var a="";E&&E.getId()&&(a=E.getId()||"");E&&E.getXtags()&&(E=E.getXtags(),E=E.replace(h,""),a=a.concat(`;${E}`));this.D==="HLS"&&(a="");this.K.D5(D?d:"",D?a:"",w)}F7(E,D){E=(E||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");E.length>0&&this.K.F7(E,D)}});})(_yt_player);
